import { randomUUID } from 'node:crypto';
import type { JobDatabase } from './db.js';
import type { ApplicationStatus } from '../domain/types.js';
import { canTransitionApplication } from '../domain/statusTransitions.js';
import { classifyOutcomeMessage, type SuggestedOutcome } from '../domain/outcomeInbox.js';

type ItemRow={id:string;application_id:string;message_excerpt:string;suggested_outcome:SuggestedOutcome;confidence:number;status:string;confirmed_outcome:string|null;created_at:string;resolved_at:string|null;company:string|null;title:string|null};
export type OutcomeInboxItem={id:string;applicationId:string;company:string|null;title:string|null;messageExcerpt:string;suggestedOutcome:SuggestedOutcome;confidence:number;status:string;confirmedOutcome:string|null;createdAt:string;resolvedAt:string|null};
const out=(r:ItemRow):OutcomeInboxItem=>({id:r.id,applicationId:r.application_id,company:r.company,title:r.title,messageExcerpt:r.message_excerpt,suggestedOutcome:r.suggested_outcome,confidence:r.confidence,status:r.status,confirmedOutcome:r.confirmed_outcome,createdAt:r.created_at,resolvedAt:r.resolved_at});
function mapping(x:SuggestedOutcome):{status:ApplicationStatus;outcomeType:string}|null{if(x==='REJECTION')return{status:'CLOSED',outcomeType:'REJECTED'};if(x==='INTERVIEW')return{status:'INTERVIEW',outcomeType:'INTERVIEW'};if(x==='OFFER')return{status:'OFFER',outcomeType:'OFFER'};if(x==='RECRUITER_CONTACT')return{status:'CONTACTED',outcomeType:'CONTACTED'};return null;}
export class OutcomeInboxService{
 constructor(private readonly database:JobDatabase){}
 list(userId:string):OutcomeInboxItem[]{return (this.database.db.prepare(`SELECT i.*,j.company,j.title FROM outcome_inbox_items i JOIN applications a ON a.id=i.application_id JOIN jobs j ON j.id=a.job_id WHERE i.user_id=? ORDER BY i.created_at DESC`).all(userId) as unknown as ItemRow[]).map(out);}
 ingest(userId:string,applicationId:string,text:string):OutcomeInboxItem{const app=this.database.db.prepare(`SELECT a.id,j.company,j.title FROM applications a JOIN jobs j ON j.id=a.job_id WHERE a.id=? AND a.user_id=?`).get(applicationId,userId) as {id:string;company:string|null;title:string|null}|undefined;if(!app)throw new Error('Nie znaleziono aplikacji.');const clean=text.trim();if(clean.length<10||clean.length>5000)throw new Error('Wiadomość musi mieć od 10 do 5000 znaków.');const c=classifyOutcomeMessage(clean),id=randomUUID(),now=new Date().toISOString(),excerpt=clean.slice(0,500);this.database.db.prepare(`INSERT INTO outcome_inbox_items(id,user_id,application_id,source,message_excerpt,suggested_outcome,confidence,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,userId,applicationId,'MANUAL_TEXT',excerpt,c.outcome,c.confidence,'PENDING',now);return{id,applicationId,company:app.company,title:app.title,messageExcerpt:excerpt,suggestedOutcome:c.outcome,confidence:c.confidence,status:'PENDING',confirmedOutcome:null,createdAt:now,resolvedAt:null};}
 resolve(userId:string,id:string,action:'CONFIRM'|'DISMISS'):OutcomeInboxItem{const row=this.database.db.prepare(`SELECT i.*,j.company,j.title FROM outcome_inbox_items i JOIN applications a ON a.id=i.application_id JOIN jobs j ON j.id=a.job_id WHERE i.id=? AND i.user_id=?`).get(id,userId) as ItemRow|undefined;if(!row)throw new Error('Nie znaleziono sugestii.');if(row.status!=='PENDING')return out(row);const now=new Date().toISOString();if(action==='DISMISS'){this.database.db.prepare(`UPDATE outcome_inbox_items SET status='DISMISSED',resolved_at=? WHERE id=? AND user_id=?`).run(now,id,userId);return{...out(row),status:'DISMISSED',resolvedAt:now};}const m=mapping(row.suggested_outcome);if(!m)throw new Error('Brak konkretnego wyniku do potwierdzenia.');const a=this.database.db.prepare('SELECT status FROM applications WHERE id=? AND user_id=?').get(row.application_id,userId) as {status:ApplicationStatus}|undefined;if(!a)throw new Error('Nie znaleziono aplikacji.');if(!canTransitionApplication(a.status,m.status))throw new Error(`Niedozwolona zmiana statusu: ${a.status} → ${m.status}`);const tx=this.database.db.transaction(()=>{this.database.db.prepare('UPDATE applications SET status=?,current_stage=?,updated_at=? WHERE id=? AND user_id=?').run(m.status,m.status,now,row.application_id,userId);this.database.db.prepare('INSERT INTO outcomes(id,application_id,outcome_type,occurred_at,source,confidence,confirmed_by_user,created_at) VALUES(?,?,?,?,?,?,1,?)').run(randomUUID(),row.application_id,m.outcomeType,now,'OUTCOME_INBOX',row.confidence,now);this.database.db.prepare(`UPDATE outcome_inbox_items SET status='CONFIRMED',confirmed_outcome=?,resolved_at=? WHERE id=? AND user_id=?`).run(m.outcomeType,now,id,userId);});tx();return{...out(row),status:'CONFIRMED',confirmedOutcome:m.outcomeType,resolvedAt:now};}
}
