import { faroPgFixture } from '../src/tests/faro-pg-fixture.js';
import { test, expect, type Page } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { faroFixture, offerInput } from '../src/tests/faro-fixture.js';
import { proposeInterview } from '../src/server/faro/interviewProposalModel.js';
import { changeInterviewSchedule } from '../src/server/faro/interviewScheduleModel.js';
import { InterviewService } from '../src/server/faro/interviewService.js';

async function login(page: Page, base: string, email: string) {
  await page.goto(base);
  await page.locator('#loginForm [name=email]').fill(email);
  await page.locator('#loginForm [name=password]').fill('Bezpieczne123');
  await page.getByRole('button', { name: 'Zaloguj się', exact: true }).click();
  await expect(page.locator('.f-brand')).toBeVisible();
  await expect(page.locator('#f-content')).toHaveAttribute('aria-busy', 'false');
}
test('Faro real candidate and employer process, private watch, economics and responsive workspace', async ({ page }, info) => {
  const f = process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture(); f.app.config.appOrigin = f.base;
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const retired: string[] = []; page.on('request', r => { if (/\/api\/(cv|career-truth|billing|applications|job-search)/.test(r.url())) retired.push(r.url()); });
  try {
    const employer = await f.user('BrowserEmployer'), candidate = await f.user('BrowserCandidate'), admin = await f.user('BrowserAdmin');
    if('query' in f.app.db)await f.app.db.query("UPDATE users SET role='ADMIN' WHERE id=$1",[admin.id]);else f.app.db.db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(admin.id);
    const org = await f.request<{ id: string }>('/api/faro/organizations', employer.cookie, 'POST', { name: 'Faro test · Pracownia' }, 201);
    await f.request(`/api/faro/organizations/${org.id}/verify`, admin.cookie, 'POST', { note: 'Synthetic browser fixture verification' });
    const draft = await f.request<{ id: string }>(`/api/faro/organizations/${org.id}/offers`, employer.cookie, 'POST', offerInput(employer.id), 201);
    await f.request(`/api/faro/offers/${draft.id}/lifecycle`, employer.cookie, 'POST', { action: 'REVIEW', expectedVersion: 1 });
    await f.request(`/api/faro/offers/${draft.id}/lifecycle`, employer.cookie, 'POST', { action: 'PUBLISH', expectedVersion: 2, confirmed: true });
    await login(page, f.base, candidate.email);
    await page.getByRole('link', { name: 'Profil', exact: true }).click();
    await page.locator('[data-form=profile] [name=firstName]').fill('Anna');
    await page.locator('[data-form=profile] [name=phone]').fill('+48500100200');
    await page.getByRole('button', { name: 'Zapisz profil', exact: true }).click();
    await expect(page.locator('#f-status')).toHaveText('Zapisano.');
    const learning=page.locator('[data-form=learning]').filter({has:page.locator('[name=mode][value=WANTS_TO_LEARN]')});
    await expect(learning.locator('[name=skillId] option')).toHaveCount(50);
    await learning.locator('[data-skill-search]').fill('zzzz_no_matching_concept');
    await expect(learning.locator('[data-skill-status]')).toHaveText('Brak wyników. Spróbuj innej nazwy.');
    await expect(learning.locator('[name=skillId]')).toHaveValue('');
    await learning.locator('[data-skill-search]').fill('POSLUGIWAC SIE JEZYKIEM TURECKIM W MOWIE');
    await expect(learning.locator('[name=skillId] option')).toHaveCount(2);
    await expect(learning.locator('[name=skillId]')).toHaveValue('');
    await learning.locator('[name=skillId]').selectOption('esco:29c954f2-ed17-4900-bba5-4cfd294f3680');
    await learning.getByLabel('Prywatny kontekst praktyki (opcjonalnie)',{exact:true}).fill('PRIVATE_BROWSER_CONTEXT <img src=x onerror=alert(1)>');
    await learning.getByRole('button',{name:'Zapisz kierunek',exact:true}).click();
    await expect(page.getByRole('button',{name:'Usuń kierunek: posługiwać się językiem tureckim w mowie',exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByText('Prywatny kontekst: PRIVATE_BROWSER_CONTEXT <img src=x onerror=alert(1)>',{exact:true})).toBeVisible();
    await expect(page.locator('.f-row img[src=x]')).toHaveCount(0);
    const privatePreview=await f.request('/api/faro/profile/preview',candidate.cookie);expect(JSON.stringify(privatePreview)).not.toContain('PRIVATE_BROWSER_CONTEXT');
    await page.getByRole('button',{name:'Usuń kierunek: posługiwać się językiem tureckim w mowie',exact:true}).click();
    await expect(page.getByRole('button',{name:'Usuń kierunek: posługiwać się językiem tureckim w mowie',exact:true})).toHaveCount(0);
    await learning.locator('[name=skillId]').selectOption('faro:legacy:4');
    await learning.locator('[name=quantity]').fill('3');await learning.locator('[name=unit]').selectOption('PROJECTS');
    await learning.getByRole('button',{name:'Zapisz kierunek',exact:true}).click();
    await expect(page.getByRole('button',{name:'Usuń kierunek: SQL',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Usuń kierunek: SQL',exact:true}).click();
    await expect(page.getByRole('button',{name:'Usuń kierunek: SQL',exact:true})).toHaveCount(0);
    expect((await f.request<{learning:unknown[]}>('/api/faro/profile',candidate.cookie)).learning).toHaveLength(0);
    await page.locator('[data-form=activity] [name=description]').fill('PRIVATE_BROWSER_ERASURE SQL');
    await page.getByRole('button',{name:'Zapisz i sprawdź propozycje',exact:true}).click();
    await expect(page.getByText('PRIVATE_BROWSER_ERASURE SQL',{exact:true})).toBeVisible();
    await page.getByText('SQL — potwierdź lub odrzuć',{exact:true}).click();
    await expect(page.getByText(/Lokalne reguły Faro · local-question-rules-v3/)).toBeVisible();
    await page.getByRole('button',{name:'To nie opisuje mojej praktyki',exact:true}).click();
    await page.getByText('Historia decyzji o propozycjach',{exact:true}).click();
    await expect(page.getByText(/SQL · Odrzucono propozycję/)).toBeVisible();
    await page.getByText('Usuń prywatny opis',{exact:true}).click();
    await page.getByLabel('Potwierdzam usunięcie tego opisu i jego propozycji.').check();
    await page.getByRole('button',{name:'Usuń opis i propozycje',exact:true}).click();
    await expect(page.getByText('PRIVATE_BROWSER_ERASURE SQL',{exact:true})).toHaveCount(0);
    const removedActivity=await f.request<{activities:unknown[];proposals:unknown[]}>('/api/faro/profile',candidate.cookie);
    expect(removedActivity.activities).toHaveLength(0);expect(removedActivity.proposals).toHaveLength(0);
    await page.getByText('Dodaj kompetencję', { exact: true }).click();
    await page.getByText('Przykłady zadań dla poziomów: Obsługa klienta',{exact:true}).click();
    await expect(page.getByText('Samodzielnie wyjaśniam typową sprawę klienta według procedury i potwierdzam uzgodniony kolejny krok.',{exact:true})).toBeVisible();
    await expect(page.getByText(/Autorskie wskazówki FARO do walidacji/).first()).toBeVisible();
    const claim = page.locator('[data-form=claim]');
    await claim.locator('[name=skillId]').selectOption('faro:activity:customer-service');
    await claim.locator('[name=level]').selectOption('INDEPENDENT');
    await claim.locator('[name=confirmed]').check();
    await claim.getByRole('button', { name: 'Zapisz deklarację' }).click();
    await expect(page.locator('.f-row').filter({hasText:'Obsługa klienta'})).toBeVisible();
    const constraints=page.locator('[data-form=constraints]');
    await constraints.locator('[name=active]').check();
    await constraints.locator('[name=workModels][value=REMOTE]').check();
    await constraints.locator('[name=noNights]').check();
    await constraints.locator('[name=salaryEnabled]').check();
    await constraints.locator('[name=salaryMinimum]').fill('5500');
    await constraints.getByRole('button',{name:'Zapisz prywatne granice'}).click();
    await expect(page.locator('[data-form=constraints] [name=active]')).toBeChecked();
    await page.reload();
    await expect(page.locator('[data-form=constraints] [name=salaryMinimum]')).toHaveValue('5500');
    await page.locator('[data-form=constraints] [name=commuteEnabled]').check();await page.locator('[data-form=constraints] [name=maxCommuteMinutes]').fill('45');
    await page.getByRole('button',{name:'Zapisz prywatne granice'}).click();await expect(page.locator('#f-status')).toHaveText('Zapisano.');await page.reload();await expect(page.locator('[data-form=constraints] [name=maxCommuteMinutes]')).toHaveValue('45');
    await page.getByRole('link', { name: 'Możliwości', exact: true }).click();
    await expect(page.locator('.f-offer-card')).toHaveCount(0);
    await page.getByLabel('Pokaż też oferty z nieznanymi warunkami').check();await page.getByRole('button',{name:'Filtruj',exact:true}).click();await expect(page.getByText('Warunki częściowo nieznane',{exact:true})).toBeVisible();
    await page.locator(`.f-offer-card[href="#offers/${draft.id}"]`).click();
    await expect(page.getByRole('heading', { name: 'Droga do tej pracy' })).toBeVisible();
    await expect(page.getByText('Bez nocy: warunek spełniony',{exact:true})).toBeVisible();
    await expect(page.getByText('Minimum wynagrodzenia: warunek spełniony',{exact:true})).toBeVisible();
    await expect(page.getByText('Maksymalny dojazd: brak informacji — nie wiemy',{exact:true})).toBeVisible();
    await expect(page.getByText('Wymagane · deklarujesz wymagany poziom', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Obserwuj prywatnie' }).click();
    await expect(page.getByRole('button', { name: 'Przestań obserwować' })).toBeVisible();
    await page.getByRole('button',{name:'Wycisz alerty obserwowanej oferty'}).click();
    await expect(page.getByRole('button',{name:'Włącz alerty obserwowanej oferty'})).toBeVisible();
    await page.getByRole('button',{name:'Włącz alerty obserwowanej oferty'}).click();
    await expect(page.getByRole('button',{name:'Wycisz alerty obserwowanej oferty'})).toBeVisible();
    const noInterest = await f.request<{processes:unknown[]}>('/api/faro/processes', candidate.cookie);
    expect(noInterest.processes).toHaveLength(0);
    await page.getByRole('button', { name: 'Zgłoś zainteresowanie', exact: true }).click();
    const preview = page.getByRole('dialog'); await expect(preview.getByRole('heading',{name:'Anna',exact:true})).toBeVisible();
    await preview.locator('[name=projectionConfirmed]').check();
    await preview.getByRole('button',{name:'Zgłoś zainteresowanie',exact:true}).click();
    await expect(page.locator('.f-detail').getByText('Zainteresowanie zgłoszone',{exact:true})).toBeVisible();
    const {processes} = await f.request<{processes:Array<{id:string}>}>('/api/faro/processes',candidate.cookie);
    expect(processes).toHaveLength(1); const processId=processes[0]!.id;
    await page.goto(`${f.base}/#economics/${draft.id}`);
    await page.locator('[name=netMin]').fill('4200'); await page.locator('[name=netMax]').fill('4700');
    await page.locator('[name=commuteCost]').fill('300'); await page.locator('[name=commuteMinutes]').fill('45');
    await page.locator('[name=assumptions]').fill('Własny miesięczny koszt dojazdów, pełen miesiąc.');
    await page.getByRole('button',{name:'Zapisz prywatny szacunek'}).click();
    await expect(page.getByRole('heading',{name:'Wynik scenariusza'})).toBeVisible();
    await page.goto(`${f.base}/#offers/${draft.id}`);
    await expect(page.getByText('Maksymalny dojazd: warunek spełniony',{exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Możliwości',exact:true}).click();await page.getByLabel('Pokaż też oferty z nieznanymi warunkami').uncheck();await page.getByRole('button',{name:'Filtruj',exact:true}).click();await expect(page.locator('.f-offer-card')).toHaveCount(1);await page.goto(`${f.base}/#offers/${draft.id}`);
    await page.getByRole('button',{name:'Dodaj do porównania'}).click();
    await page.getByRole('link',{name:'Porównanie',exact:true}).click();
    await expect(page.getByRole('table')).toBeVisible();
    const comparisonRow=(name:string)=>page.getByRole('row').filter({has:page.getByRole('rowheader',{name,exact:true})});
    await expect(comparisonRow('Godziny pracy')).toContainText('8:00–16:00');
    await expect(comparisonRow('Praca nocna')).toContainText('Nie');
    await expect(comparisonRow('Lokalizacja')).toContainText('Cała Polska');
    await expect(comparisonRow('Źródło prywatnego szacunku')).toContainText('Własny szacunek');
    await expect(comparisonRow('Wariant prywatnego scenariusza')).toContainText('aktualne warunki');
    await expect(comparisonRow('Wsparcie nauki')).toContainText('Opiekun');
    expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
    await page.setViewportSize({width:320,height:720});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.goto(`${f.base}/#offers/${draft.id}`);
    await expect(page.getByRole('heading',{name:'Droga do tej pracy'})).toBeVisible();
    const accessibility = await new AxeBuilder({page}).include('#appView').analyze();
    expect(accessibility.violations).toEqual([]);
    await page.screenshot({path: info.outputPath('faro-workspace.png'),fullPage:true});
    await page.setViewportSize({width:320,height:720});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await expect(page.locator('.f-list')).toBeHidden(); await page.getByRole('link',{name:'← Wróć do listy'}).click();
    await expect(page.locator('.f-list')).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();
    await login(page,f.base,employer.email);
    await page.locator('#f-role').selectOption('employer');
    await page.getByRole('link',{name:'Organizacja',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Rzetelność procesu — fakty'})).toBeVisible();
    await expect(page.getByText('Brak dojrzałej próby',{exact:true})).toBeVisible();
    await expect(page.locator('.f-facts dt').filter({hasText:'Zgłoszenia w oknie'}).locator('xpath=following-sibling::dd[1]')).toHaveText('1');
    expect((await new AxeBuilder({page}).include('#appView').analyze()).violations).toEqual([]);
    await page.getByRole('link',{name:'Oferty',exact:true}).click();
    await page.locator(`.f-offer-card[href="#employer/${draft.id}"]`).click();
    await page.locator('.f-detail').getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await page.getByRole('heading',{name:'Anna',exact:true}).click();
    await page.locator('[data-form=process-command] [name=command]').selectOption('ADVANCE');
    await page.locator('[name=nextAction]').fill('Rozmowa o praktyce obsługi klienta');
    await page.locator('[name=dueAt]').fill('2099-01-01T12:00');
    const confirmation=page.locator('[data-form=process-command] [name=confirmed]');
    const target=await confirmation.boundingBox();expect(target!.width).toBeGreaterThanOrEqual(24);expect(target!.height).toBeGreaterThanOrEqual(24);
    expect(await confirmation.evaluate(el=>getComputedStyle(el).padding)).toBe('0px');
    await confirmation.check();
    await page.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('W toku',{exact:true})).toBeVisible();
    const p=await f.request<{stage:string;contactGrant:unknown}>(`/api/faro/processes/${processId}`,candidate.cookie);
    expect(p.stage).toBe('ACCEPTED_TO_NEXT_STAGE'); expect(p.contactGrant).toBeNull();
    await page.getByText('Zaproponuj termin rozmowy',{exact:true}).click();
    const propose=page.locator('[data-form=interview-propose]');
    await propose.locator('[name=startsAt]').fill('2099-01-03T12:00');
    await propose.locator('[name=endsAt]').fill('2099-01-03T13:00');
    await propose.locator('[name=confirmBy]').fill('2099-01-02T12:00');
    await propose.locator('[name=location]').fill('Rozmowa online');
    await propose.locator('[name=meetingUrl]').fill('https://example.pl/meeting');
    await propose.locator('[name=confirmed]').check();
    await propose.getByRole('button',{name:'Zaproponuj rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Termin zaproponowany',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();
    await login(page,f.base,candidate.email);await page.goto(`${f.base}/#processes/${processId}`);
    await page.getByRole('button',{name:'Udostępnij telefon tej rekrutacji',exact:true}).click();
    const phoneDialog=page.getByRole('dialog');await expect(phoneDialog).toContainText('+48500100200');
    expect((await f.request<{contactGrant:unknown}>(`/api/faro/processes/${processId}`,candidate.cookie)).contactGrant).toBeNull();
    await phoneDialog.locator('[name=phoneConfirmed]').check();
    await phoneDialog.getByRole('button',{name:'Potwierdź udostępnienie',exact:true}).click();
    await expect(page.getByRole('button',{name:'Cofnij udostępnienie telefonu'})).toBeVisible();
    expect((await f.request<{phone:string}>(`/api/faro/processes/${processId}/phone`,employer.cookie)).phone).toBe('+48500100200');
    await page.getByRole('button',{name:'Cofnij udostępnienie telefonu'}).click();
    await expect(page.getByRole('button',{name:'Udostępnij telefon tej rekrutacji',exact:true})).toBeVisible();
    await f.request(`/api/faro/processes/${processId}/phone`,employer.cookie,'GET',undefined,403);
    const change=page.locator('[data-form=interview-change]');
    await change.locator('[name=command]').selectOption('CONFIRM');await change.locator('[name=confirmed]').check();
    await change.getByRole('button',{name:'Zapisz rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Rozmowa potwierdzona',{exact:true})).toBeVisible();
    const calendarDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Dodaj do kalendarza'}).click();
    const calendar=await calendarDownload;const ics=await readFile((await calendar.path())!,'utf8');
    expect(ics).toContain('BEGIN:VCALENDAR');expect(ics).not.toContain('Anna');expect(ics).not.toContain('ATTENDEE');
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await change.locator('[name=command]').selectOption('CANCEL');await change.locator('[name=reason]').selectOption('RESCHEDULE');await change.locator('[name=confirmed]').check();
    await change.getByRole('button',{name:'Zapisz rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Anulowane',{exact:true})).toBeVisible();
    expect(errors).toEqual([]); expect(retired).toEqual([]);
  } finally { try { if (!page.isClosed()) { await page.screenshot({path:info.outputPath('final-state.png'),fullPage:true}); await page.goto('about:blank'); } } finally { await f.close(); } }
});

test('clarification workspace shares only structured declarations and keeps profile snapshot unchanged',async({page})=>{
  const f=process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('ClarifyEmployer'),candidate=await f.user('ClarifyCandidate');
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Rozmowa o kompetencjach'},201);
    if('query' in f.app.db)await f.app.db.query("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=$1",[org.id]);else f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',expectedVersion:0,availability:{kind:'IMMEDIATE'}});
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',offerInput(employer.id),201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    const preview=await f.request<{confirmationToken:string}>('/api/faro/profile/preview-confirmation',candidate.cookie);
    const p=await f.request<{id:string}>(`/api/faro/offers/${offer.id}/interest`,candidate.cookie,'POST',{offerVersion:1,projectionConfirmed:true,confirmationToken:preview.confirmationToken,idempotencyKey:'browser-clarify-interest'},201);
    await login(page,f.base,employer.email);await page.goto(`${f.base}/#processes/${p.id}`);
    const command=page.locator('[data-form=process-command]');
    await command.locator('[name=command]').selectOption('CLARIFY');
    await command.locator('[name=questionTopic]').selectOption('REQUIREMENT');
    await command.locator('[name=questionRequirementId]').selectOption('req-customer');
    await command.locator('[name=dueAt]').fill('2099-01-01T12:00');await command.locator('[name=confirmed]').check();
    await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('Pytanie do kandydata',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);await page.goto(`${f.base}/#processes/${p.id}`);
    await expect(command.locator('[name=answer]')).toHaveCount(0);
    await command.locator('[name=command]').selectOption('ANSWER');await command.locator('[name=responseKind]').selectOption('DECLARE_SKILL');
    await command.locator('[name=level]').selectOption('INDEPENDENT');await command.locator('[name=source]').selectOption('WORK');
    await command.locator('[name=quantity]').fill('12');await command.locator('[name=unit]').selectOption('MONTHS');await command.locator('[name=confirmed]').check();
    await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-timeline')).toContainText('Deklaruję kompetencję');
    const view=await f.request<{projection:{skillClaims:unknown[]};stage:string}>(`/api/faro/processes/${p.id}`,employer.cookie);
    expect(view.projection.skillClaims).toHaveLength(0);expect(view.stage).toBe('AWAITING_EMPLOYER');
    await command.locator('[name=command]').selectOption('WITHDRAW');await command.locator('[name=confirmed]').check();await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('Wycofane',{exact:true})).toBeVisible();
    await page.goto(`${f.base}/#offers/${offer.id}`);await page.getByRole('button',{name:'Zgłoś ponownie zainteresowanie'}).click();
    const dialog=page.getByRole('dialog');await dialog.locator('[name=projectionConfirmed]').check();await dialog.locator('[name=renewalConfirmed]').check();
    await dialog.getByRole('button',{name:'Zgłoś zainteresowanie',exact:true}).click();
    await expect(page.getByRole('link',{name:'Otwórz poprzedni proces'})).toBeVisible();
    const history=await f.request<{processes:Array<{id:string;previousInterestId:string|null}>}>('/api/faro/processes',candidate.cookie);
    expect(history.processes).toHaveLength(2);expect(history.processes.find(process=>process.id!==p.id)?.previousInterestId).toBe(p.id);
  } finally {await page.goto('about:blank');await f.close();}
});

test('case workspace supports private explanations from both sides, independent review and candidate appeal',async({page})=>{
  const f=process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('CaseBrowserEmployer'),candidate=await f.user('CaseBrowserCandidate'),admin=await f.user('CaseBrowserModerator');
    if('query' in f.app.db)await f.app.db.query("UPDATE users SET role='ADMIN' WHERE id=$1",[admin.id]);else f.app.db.db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(admin.id);
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Sprawa po rozmowie'},201);
    if('query' in f.app.db)await f.app.db.query("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=$1",[org.id]);else f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',expectedVersion:0,availability:{kind:'IMMEDIATE'}});
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',offerInput(employer.id),201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    const preview=await f.request<{confirmationToken:string}>('/api/faro/profile/preview-confirmation',candidate.cookie);
    const p=await f.request<{id:string}>(`/api/faro/offers/${offer.id}/interest`,candidate.cookie,'POST',{offerVersion:1,projectionConfirmed:true,confirmationToken:preview.confirmationToken,idempotencyKey:'case-browser-interest'},201);
    await f.request(`/api/faro/processes/${p.id}/commands`,employer.cookie,'POST',{command:'ADVANCE',nextAction:'Uzgodnijmy rozmowę',dueAt:new Date(Date.now()+86400000).toISOString(),expectedVersion:1,idempotencyKey:'case-browser-advance'});
    // A controlled fixture clock reaches the meeting outcome without a wall-clock sleep.
    const now=Date.now(),asOf=new Date(now-3*3600000).toISOString();
    const proposal={startsAt:new Date(now-2*3600000).toISOString(),endsAt:new Date(now-3600000).toISOString(),confirmBy:new Date(now-2.5*3600000).toISOString(),timezone:'Europe/Warsaw',location:'Online',confirmed:true,expectedVersion:2,idempotencyKey:'case-browser-propose'};
    const meeting='query' in f.app.db?await proposeInterview(f.app.db,employer.id,p.id,proposal,asOf,()=>{}):new InterviewService(f.app.db,()=>new Date(asOf)).propose(employer.id,p.id,proposal);
    const confirmation={command:'CONFIRM',confirmed:true,expectedVersion:1,processVersion:3,idempotencyKey:'case-browser-confirm'};
    if('query' in f.app.db)await changeInterviewSchedule(f.app.db,candidate.id,meeting.id,confirmation,asOf,()=>{});else new InterviewService(f.app.db,()=>new Date(asOf)).change(candidate.id,meeting.id,confirmation);
    await f.request(`/api/faro/interviews/${meeting.id}`,employer.cookie,'POST',{command:'DISPUTE',reason:'NO_SHOW',confirmed:true,expectedVersion:2,processVersion:4,idempotencyKey:'case-browser-dispute'});
    await login(page,f.base,candidate.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    const explanation=page.locator('[data-form=case-explain]');await explanation.locator('[name=statement]').fill('Prywatna informacja medyczna kandydata.');await explanation.getByRole('button',{name:'Przekaż wyjaśnienie'}).click();
    await expect(page.locator('#f-content')).toContainText('Prywatna informacja medyczna kandydata.');
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,employer.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).not.toContainText('informacja medyczna');
    await explanation.locator('[name=statement]').fill('Prywatne wyjaśnienie firmy dotyczące połączenia.');await explanation.getByRole('button',{name:'Przekaż wyjaśnienie'}).click();
    await expect(page.locator('#f-content')).toContainText('Prywatne wyjaśnienie firmy');
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,admin.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).toContainText('informacja medyczna');await expect(page.locator('#f-content')).toContainText('wyjaśnienie firmy');
    const review=page.locator('[data-form=case-review]');await review.locator('[name=state]').selectOption('EVIDENCE_REVIEW');await review.locator('[name=decision]').fill('Prywatna notatka moderatora o sprawdzeniu materiału.');await review.locator('[name=reviewAt]').fill('2099-01-03T12:00');await review.locator('[name=explanationDueAt]').fill('2099-01-02T12:00');await review.getByRole('button',{name:'Zapisz przegląd'}).click();
    await expect(page.locator('.f-chip')).toHaveText('EVIDENCE_REVIEW');
    await review.locator('[name=state]').selectOption('NO_ACTION');await review.locator('[name=decision]').fill('Prywatna notatka moderatora o braku naruszenia.');await review.locator('[name=decisionCode]').selectOption('NO_VIOLATION_CONFIRMED');await review.locator('[name=reviewAt]').fill('2099-01-03T12:00');await review.getByRole('button',{name:'Zapisz przegląd'}).click();
    await expect(page.locator('.f-chip')).toHaveText('NO_ACTION');await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).not.toContainText('notatka moderatora');
    const appeal=page.locator('[data-form=appeal]');await appeal.locator('[name=statement]').fill('Proszę o ponowne prywatne sprawdzenie rozbieżności.');await appeal.getByRole('button',{name:'Zapisz odwołanie'}).click();await expect(page.locator('.f-chip')).toHaveText('APPEAL');
  }finally{await page.goto('about:blank');await f.close();}
});

test('privacy workspace exports own data and requires reauthentication before erasure',async({page})=>{
  const f=process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture(); f.app.config.appOrigin=f.base;
  try{
    const candidate=await f.user('PrivacyBrowser');
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',availability:{kind:'IMMEDIATE'},expectedVersion:0});
    await login(page,f.base,candidate.email);
    await page.getByRole('link',{name:'Prywatność',exact:true}).click();
    const downloaded=page.waitForEvent('download');
    await page.getByRole('button',{name:'Pobierz moje dane'}).click();
    const file=await downloaded;
    const payload=JSON.parse(await readFile((await file.path())!,'utf8')) as {faro:{faro_profiles:Array<{first_name:string}>}};
    expect(payload.faro.faro_profiles[0]!.first_name).toBe('Anna');
    const deletion=page.locator('[data-form=delete-account]');
    await deletion.locator('[name=confirmation]').fill('USUŃ KONTO');
    await deletion.locator('[name=password]').fill('BledneHaslo123');
    await deletion.locator('[name=confirmed]').check();
    await deletion.getByRole('button',{name:'Usuń moje konto'}).click();
    await expect(deletion.locator('.f-form-message')).toContainText('poprawne aktualne hasło');
    await expect(page.locator('.f-brand')).toBeVisible();
    await deletion.locator('[name=password]').fill('Bezpieczne123');
    await deletion.getByRole('button',{name:'Usuń moje konto'}).click();
    await expect(page.locator('#loginForm')).toBeVisible();
    await expect(page.locator('#authMessage')).toHaveText('Konto i dane zostały usunięte.');
    await f.request('/api/me',candidate.cookie,'GET',undefined,401);
  }finally{if(!page.isClosed())await page.goto('about:blank'); await f.close();}
});

test('Faro assessment assignment and reviewed result through real workspace',async({page})=>{
  const f=process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('QuizEmployer'),candidate=await f.user('QuizCandidate');
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Pracownia quizu'},201);
    if('query' in f.app.db)await f.app.db.query("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=$1",[org.id]);else f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',expectedVersion:0,availability:{kind:'IMMEDIATE'}});
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',offerInput(employer.id),201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    const preview=await f.request<{confirmationToken:string}>('/api/faro/profile/preview-confirmation',candidate.cookie);
    const process=await f.request<{id:string}>(`/api/faro/offers/${offer.id}/interest`,candidate.cookie,'POST',{offerVersion:1,projectionConfirmed:true,confirmationToken:preview.confirmationToken,idempotencyKey:'quiz-interest'},201);
    await f.request(`/api/faro/processes/${process.id}/commands`,employer.cookie,'POST',{command:'ADVANCE',nextAction:'Krótki quiz praktyczny',dueAt:new Date(Date.now()+86400000).toISOString(),expectedVersion:1,idempotencyKey:'quiz-advance'});
    await login(page,f.base,employer.email);
    await page.locator('#f-role').selectOption('employer');
    await page.goto(`${f.base}/#assessment-create/${offer.id}`);
    const create=page.locator('[data-form=assessment-create]');
    await create.locator('[name=title]').fill('Quiz obsługi klienta');
    await create.locator('[name=prompt]').fill('Co robisz najpierw?');
    await create.locator('[name=options]').fill('Słucham klienta\nPrzerywam klientowi');
    await create.getByRole('button',{name:'Zapisz szkic'}).click();
    await page.locator('[data-form=assessment-approve] [name=confirmed]').check();
    await page.getByRole('button',{name:'Przekaż do review'}).click();
    await expect(page.getByRole('button',{name:'Zatwierdź',exact:true})).toBeVisible();
    await page.locator('[data-form=assessment-approve] [name=confirmed]').check();
    await page.getByRole('button',{name:'Zatwierdź',exact:true}).click();
    await expect(page.getByText('Zatwierdzony',{exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Utwórz nową wersję'}).click();
    await page.getByRole('button',{name:'Dodaj zadanie',exact:true}).click();
    await page.locator('[name="prompt:1"]').fill('Jak potwierdzasz zrozumienie?');
    await page.locator('[name="options:1"]').fill('Podsumowuję potrzeby\nIgnoruję pytanie');
    await page.getByRole('button',{name:'Zapisz nowy szkic'}).click();
    await expect(page.getByText('Wersja 2',{exact:true})).toBeVisible();
    await page.locator('[data-form=assessment-approve] [name=confirmed]').check();
    await page.getByRole('button',{name:'Przekaż do review'}).click();
    await expect(page.getByRole('button',{name:'Zatwierdź',exact:true})).toBeVisible();
    await page.locator('[data-form=assessment-approve] [name=confirmed]').check();
    await page.getByRole('button',{name:'Zatwierdź',exact:true}).click();
    await expect(page.getByRole('button',{name:'Zatwierdź',exact:true})).toHaveCount(0);
    await page.goto(`${f.base}/#assessment-assign/${process.id}`);
    await page.locator('[data-form=assessment-assign] [name=deadline]').fill('2099-01-01T12:00');
    await page.getByRole('button',{name:'Przypisz',exact:true}).click();
    await expect(page.locator('.f-detail').getByText('Zaproszenie do assessmentu',{exact:true})).toBeVisible();
    const attempts=await f.request<{attempts:Array<{id:string}>}>(`/api/faro/processes/${process.id}/assessment`,candidate.cookie);
    expect(attempts.attempts).toHaveLength(1);const id=attempts.attempts[0]!.id;
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);
    await page.goto(`${f.base}/#attempts/${id}`);
    await expect(page.getByText('Liczba zadań',{exact:true})).toBeVisible();
    await expect(page.getByText(/Odpowiedzi robocze nie są pokazywane firmie/)).toBeVisible();
    await expect(page.getByText('Zgłoś problem techniczny tej próby',{exact:true})).toBeVisible();
    await expect(page.getByText('Co robisz najpierw?',{exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Rozpocznij assessment'}).click();
    await page.getByLabel('Słucham klienta',{exact:true}).check();
    await page.locator('[name=operation]').selectOption('Prześlij do oceny');
    await page.getByRole('button',{name:'Zapisz',exact:true}).click();
    await expect(page.getByText('Wynik czeka na review',{exact:true})).toBeVisible();
    await expect(page.getByRole('heading',{name:'Wynik w tej rekrutacji'})).toHaveCount(0);
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,employer.email);
    await page.locator('#f-role').selectOption('employer');await page.goto(`${f.base}/#attempts/${id}`);
    await expect(page.getByRole('heading',{name:'Odpowiedzi do przeglądu'})).toBeVisible();
    await expect(page.getByText('Odpowiedź kandydata: Słucham klienta',{exact:true})).toBeVisible();
    await expect(page.getByText(/Odpowiedź kandydata: Brak odpowiedzi/)).toBeVisible();
    await page.locator('[data-form=attempt-review] [name=note]').fill('Sprawdzono odpowiedź zgodnie z rubryką.');
    await page.locator('[data-form=attempt-review] [name=confirmed]').check();
    await page.getByRole('button',{name:'Udostępnij wynik kandydatowi'}).click();
    await expect(page.getByText('Wynik zatwierdzony',{exact:true})).toBeVisible();
    const final=await f.request<{result:{earned:number;review:string}}>(`/api/faro/attempts/${id}`,candidate.cookie);
    expect(final.result.earned).toBe(1);expect(final.result.review).toBe('FINALIZED');
    const amendment=page.locator('[data-form=attempt-amend]');
    await amendment.locator('[name=task-1]').fill('0');
    await amendment.locator('[name=reason]').fill('Ręczny przegląd koryguje punkty; pierwotny wynik pozostaje w historii.');
    await amendment.locator('[name=confirmed]').check();
    await amendment.getByRole('button',{name:'Zapisz korektę punktów'}).click();
    await expect(page.getByText(/Indywidualna korekta człowieka/)).toBeVisible();
    const amended=await f.request<{result:{earned:number;review:string;unanswered:number};resultHistory:unknown[]}>(`/api/faro/attempts/${id}`,candidate.cookie);
    expect(amended.result.earned).toBe(0);expect(amended.result.review).toBe('AMENDED');expect(amended.result.unanswered).toBe(1);expect(amended.resultHistory).toHaveLength(2);
    expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
    const definitions=await f.request<{assessments:Array<{id:string;version:number}>}>(`/api/faro/offers/${offer.id}/assessments`,employer.cookie);
    const pinned=definitions.assessments.find(d=>d.version===2)!;
    await page.goto(`${f.base}/#assessment-correction/${pinned.id}/2`);
    await page.locator('[data-form=key-preview] [name=task-1]').fill('1,2');
    await page.locator('[data-form=key-preview] [name=reason]').fill('Wspólny przegląd uznaje obie odpowiedzi pierwszego zadania.');
    await page.getByRole('button',{name:'Pokaż skutki korekty'}).click();
    await expect(page.getByText(/Wyników do korekty: 1. Indywidualnych korekt: 1./)).toBeVisible();
    await page.setViewportSize({width:320,height:880});
    expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.locator('[data-form=key-apply] [name=confirmed]').check();
    await page.locator('[data-form=key-apply] [name=replaceIndividualAmendments]').check();
    await page.getByRole('button',{name:'Zastosuj wspólną korektę'}).click();
    await expect(page.getByRole('heading',{name:'Twoje assessmenty'})).toBeVisible();
    await page.goto(`${f.base}/#attempts/${id}`);
    await expect(page.getByText(/Wynik przeliczony po wspólnej korekcie klucza/)).toBeVisible();
    const correction=page.locator('[data-form=attempt-invalidate]');
    await correction.locator('[name=reasonCode]').selectOption('AMBIGUOUS_TASK');
    await correction.locator('[name=reason]').fill('Zadanie było niejednoznaczne; wynik nie może służyć decyzji.');
    await correction.locator('[name=confirmed]').check();
    await correction.getByRole('button',{name:'Oznacz wynik jako nieważny'}).click();
    await expect(page.getByText('Wynik nieważny',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);await page.goto(`${f.base}/#attempts/${id}`);
    await expect(page.getByText(/Historyczne punkty nie są aktualną oceną/)).toBeVisible();
    await page.getByText('Historia ważności wyniku',{exact:true}).click();
    await expect(page.getByText('Zadanie było niejednoznaczne; wynik nie może służyć decyzji.',{exact:true})).toBeVisible();
    await expect(page.locator('[data-form=attempt-invalidate]')).toHaveCount(0);
    await expect(page.locator('[data-form=attempt-amend]')).toHaveCount(0);
    await expect(page.getByRole('heading',{name:'Wynik w tej rekrutacji'})).toHaveCount(0);
  }finally{await f.close();}
});

test('Faro preserves additional salary variants during edit and compares the selected economics basis',async({page})=>{
  const f=process.env.FARO_PG_BROWSER==='1'?await faroPgFixture():await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('SalaryEmployer'),candidate=await f.user('SalaryCandidate');
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Warianty wynagrodzenia'},201);
    if('query' in f.app.db)await f.app.db.query("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=$1",[org.id]);else f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    const input=offerInput(employer.id),second={...input.salary[0]!,contract:'B2B',basis:'B2B_NET_INVOICE_EXCL_VAT',min:7500,max:9000,period:'HOUR',hoursPerPeriod:1};
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',{...input,salary:[input.salary[0],second]},201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    await login(page,f.base,employer.email);await page.locator('#f-role').selectOption('employer');
    await page.goto(`${f.base}/#offer-edit/${offer.id}`);
    await expect(page.getByRole('heading',{name:'Pozostałe warianty wynagrodzenia'})).toBeVisible();
    const offerForm=page.locator('[data-form=offer]'),escoId='esco:29c954f2-ed17-4900-bba5-4cfd294f3680';
    await expect(offerForm.locator('[data-requirement-skill]')).toHaveCount(23);
    await offerForm.locator('[data-skill-search]').fill('posługiwać się językiem tureckim w mowie');
    await offerForm.locator('[name=requirementSkill]').selectOption(escoId);
    await offerForm.getByRole('button',{name:'Dodaj wybraną kompetencję',exact:true}).click();
    await offerForm.getByRole('button',{name:'Dodaj wybraną kompetencję',exact:true}).click();
    await expect(offerForm.locator('[data-requirement-skill]')).toHaveCount(24);
    await offerForm.locator(`[name="kind:${escoId}"]`).selectOption('WILL_TEACH');
    await offerForm.locator(`[name="why:${escoId}"]`).fill('Nauka języka przy wsparciu firmy.');
    await page.locator('[data-form=offer] [name=salaryMin]').fill('5600');
    await page.locator('[data-form=offer]').getByRole('button',{name:'Zapisz szkic',exact:true}).click();
    await expect(page.getByRole('link',{name:'Edytuj warunki'})).toBeVisible();
    const edited=await f.request<{revision:number;data:{salary:Array<Record<string,unknown>>;requirements:Array<{skillId:string;kind:string}>}}>(`/api/faro/offers/${offer.id}`,employer.cookie);
    expect(edited.data.salary).toHaveLength(2);expect(edited.data.salary[0]!.min).toBe(560000);expect(edited.data.salary[1]).toEqual(second);
    expect(edited.data.requirements).toHaveLength(3);
    expect(edited.data.requirements.find(r=>r.skillId===escoId)?.kind).toBe('WILL_TEACH');
    await page.goto(`${f.base}/#offer-edit/${offer.id}`);
    await expect(page.locator(`[name="kind:${escoId}"]`)).toHaveValue('WILL_TEACH');
    await expect(page.locator('[data-requirement-skill]')).toHaveCount(24);
    await page.goto(`${f.base}/#employer/${offer.id}`);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:edited.revision});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:edited.revision+1,confirmed:true});
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);
    await page.goto(`${f.base}/#economics/${offer.id}`);
    await page.locator('[name=salaryOptionIndex]').selectOption('1');
    await page.locator('[name=netMin]').fill('50');await page.locator('[name=netMax]').fill('60');
    await page.locator('[name=commuteCost]').fill('5');await page.locator('[name=assumptions]').fill('Syntetyczny koszt przypisany do jednej godziny, bez automatycznych podatków.');
    await page.getByRole('button',{name:'Zapisz prywatny szacunek'}).click();
    await expect(page.getByRole('heading',{name:'Wynik scenariusza'})).toBeVisible();
    await page.goto(`${f.base}/#offers/${offer.id}`);await page.getByRole('button',{name:'Dodaj do porównania'}).click();
    await page.getByRole('link',{name:'Porównanie',exact:true}).click();
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Brutto / faktura',exact:true})})).toContainText(/75,00.*90,00.*fakturze.*godzinę/);
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Dojazd — koszt',exact:true})})).toContainText(/5,00.*godzinę/);
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Aktualne warianty płacy',exact:true})})).toContainText(/fakturze.*godzinę/);
    const current=await f.request<{revision:number;data:Record<string,unknown>}>(`/api/faro/offers/${offer.id}`,employer.cookie);
    const changed=await f.request<{revision:number}>(`/api/faro/offers/${offer.id}`,employer.cookie,'PUT',{expectedVersion:current.revision,data:{...current.data,salary:[{...input.salary[0],min:560000},{...second,min:8500,max:10000}]}});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:changed.revision});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:changed.revision+1,confirmed:true});
    await page.goto(`${f.base}/#offers/${offer.id}`);
    await page.reload();
    await page.getByRole('button',{name:'Dodaj do porównania'}).click();
    await page.getByRole('link',{name:'Porównanie',exact:true}).click();
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Aktualne warianty płacy',exact:true})})).toContainText(/85,00.*100,00.*fakturze.*godzinę/);
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Brutto / faktura',exact:true})})).toContainText(/75,00.*90,00.*fakturze.*godzinę/);
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Wariant prywatnego scenariusza',exact:true})})).toContainText('wcześniejsze warunki');
    await expect(page.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Aktualne warianty płacy',exact:true})})).not.toContainText('Scenariusz dotyczy wcześniejszej wersji.');
    expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  }finally{await f.close();}
});
