import { test, expect, type Page } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { faroFixture, offerInput } from '../src/tests/faro-fixture.js';
import { InterviewService } from '../src/server/faro/interviewService.js';

async function login(page: Page, base: string, email: string) {
  await page.goto(base);
  await page.locator('#loginForm [name=email]').fill(email);
  await page.locator('#loginForm [name=password]').fill('Bezpieczne123');
  await page.getByRole('button', { name: 'Zaloguj się', exact: true }).click();
  await expect(page.locator('.f-brand')).toBeVisible();
  await expect(page.locator('#f-content')).toHaveAttribute('aria-busy', 'false');
}
test('Faro real candidate and employer process, private watch, economics and responsive workspace', async ({ page }, info) => {
  const f = await faroFixture(); f.app.config.appOrigin = f.base;
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const retired: string[] = []; page.on('request', r => { if (/\/api\/(cv|career-truth|billing|applications|job-search)/.test(r.url())) retired.push(r.url()); });
  try {
    const employer = await f.user('BrowserEmployer'), candidate = await f.user('BrowserCandidate'), admin = await f.user('BrowserAdmin');
    f.app.db.db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(admin.id);
    const org = await f.request<{ id: string }>('/api/faro/organizations', employer.cookie, 'POST', { name: 'Faro test · Pracownia' }, 201);
    await f.request(`/api/faro/organizations/${org.id}/verify`, admin.cookie, 'POST', { note: 'Synthetic browser fixture verification' });
    const draft = await f.request<{ id: string }>(`/api/faro/organizations/${org.id}/offers`, employer.cookie, 'POST', offerInput(employer.id), 201);
    await f.request(`/api/faro/offers/${draft.id}/lifecycle`, employer.cookie, 'POST', { action: 'REVIEW', expectedVersion: 1 });
    await f.request(`/api/faro/offers/${draft.id}/lifecycle`, employer.cookie, 'POST', { action: 'PUBLISH', expectedVersion: 2, confirmed: true });
    await login(page, f.base, candidate.email);
    await page.getByRole('link', { name: 'Profil', exact: true }).click();
    await page.locator('[data-form=profile] [name=firstName]').fill('Anna');
    await page.getByRole('button', { name: 'Zapisz profil', exact: true }).click();
    await expect(page.locator('#f-status')).toHaveText('Zapisano.');
    await page.getByText('Dodaj kompetencję', { exact: true }).click();
    const claim = page.locator('[data-form=claim]');
    await claim.locator('[name=skillId]').selectOption('faro:activity:customer-service');
    await claim.locator('[name=level]').selectOption('INDEPENDENT');
    await claim.locator('[name=confirmed]').check();
    await claim.getByRole('button', { name: 'Zapisz deklarację' }).click();
    await expect(page.locator('.f-row').filter({hasText:'Obsługa klienta'})).toBeVisible();
    await page.getByRole('link', { name: 'Możliwości', exact: true }).click();
    await page.locator(`.f-offer-card[href="#offers/${draft.id}"]`).click();
    await expect(page.getByRole('heading', { name: 'Droga do tej pracy' })).toBeVisible();
    await expect(page.getByText('Wymagane · deklarujesz wymagany poziom', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Obserwuj prywatnie' }).click();
    await expect(page.getByRole('button', { name: 'Przestań obserwować' })).toBeVisible();
    const noInterest = await f.request<{processes:unknown[]}>('/api/faro/processes', candidate.cookie);
    expect(noInterest.processes).toHaveLength(0);
    await page.getByRole('button', { name: 'Zgłoś zainteresowanie', exact: true }).click();
    const preview = page.getByRole('dialog'); await expect(preview.getByRole('heading',{name:'Anna',exact:true})).toBeVisible();
    await preview.locator('[name=projectionConfirmed]').check();
    await preview.getByRole('button',{name:'Zgłoś zainteresowanie',exact:true}).click();
    await expect(page.locator('.f-detail').getByText('Zainteresowanie zgłoszone',{exact:true})).toBeVisible();
    const {processes} = await f.request<{processes:Array<{id:string}>}>('/api/faro/processes',candidate.cookie);
    expect(processes).toHaveLength(1); const processId=processes[0]!.id;
    await page.goto(`${f.base}/#economics/${draft.id}`);
    await page.locator('[name=netMin]').fill('4200'); await page.locator('[name=netMax]').fill('4700');
    await page.locator('[name=commuteCost]').fill('300'); await page.locator('[name=commuteMinutes]').fill('45');
    await page.locator('[name=assumptions]').fill('Własny miesięczny koszt dojazdów, pełen miesiąc.');
    await page.getByRole('button',{name:'Zapisz prywatny szacunek'}).click();
    await expect(page.getByRole('heading',{name:'Wynik scenariusza'})).toBeVisible();
    await page.goto(`${f.base}/#offers/${draft.id}`);
    await page.getByRole('button',{name:'Dodaj do porównania'}).click();
    await page.getByRole('link',{name:'Porównanie',exact:true}).click();
    await expect(page.getByRole('table')).toBeVisible();
    await page.goto(`${f.base}/#offers/${draft.id}`);
    await expect(page.getByRole('heading',{name:'Droga do tej pracy'})).toBeVisible();
    const accessibility = await new AxeBuilder({page}).include('#appView').analyze();
    expect(accessibility.violations).toEqual([]);
    await page.screenshot({path: info.outputPath('faro-workspace.png'),fullPage:true});
    await page.setViewportSize({width:320,height:720});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await expect(page.locator('.f-list')).toBeHidden(); await page.getByRole('link',{name:'← Wróć do listy'}).click();
    await expect(page.locator('.f-list')).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();
    await login(page,f.base,employer.email);
    await page.locator('#f-role').selectOption('employer');
    await page.locator(`.f-offer-card[href="#employer/${draft.id}"]`).click();
    await page.locator('.f-detail').getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await page.getByRole('heading',{name:'Anna',exact:true}).click();
    await page.locator('[data-form=process-command] [name=command]').selectOption('ADVANCE');
    await page.locator('[name=nextAction]').fill('Rozmowa o praktyce obsługi klienta');
    await page.locator('[name=dueAt]').fill('2099-01-01T12:00');
    await page.locator('[data-form=process-command] [name=confirmed]').check();
    await page.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('W toku',{exact:true})).toBeVisible();
    const p=await f.request<{stage:string;contactGrant:unknown}>(`/api/faro/processes/${processId}`,candidate.cookie);
    expect(p.stage).toBe('ACCEPTED_TO_NEXT_STAGE'); expect(p.contactGrant).toBeNull();
    await page.getByText('Zaproponuj termin rozmowy',{exact:true}).click();
    const propose=page.locator('[data-form=interview-propose]');
    await propose.locator('[name=startsAt]').fill('2099-01-03T12:00');
    await propose.locator('[name=endsAt]').fill('2099-01-03T13:00');
    await propose.locator('[name=confirmBy]').fill('2099-01-02T12:00');
    await propose.locator('[name=location]').fill('Rozmowa online');
    await propose.locator('[name=meetingUrl]').fill('https://example.pl/meeting');
    await propose.locator('[name=confirmed]').check();
    await propose.getByRole('button',{name:'Zaproponuj rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Termin zaproponowany',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();
    await login(page,f.base,candidate.email);await page.goto(`${f.base}/#processes/${processId}`);
    const change=page.locator('[data-form=interview-change]');
    await change.locator('[name=command]').selectOption('CONFIRM');await change.locator('[name=confirmed]').check();
    await change.getByRole('button',{name:'Zapisz rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Rozmowa potwierdzona',{exact:true})).toBeVisible();
    const calendarDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Dodaj do kalendarza'}).click();
    const calendar=await calendarDownload;const ics=await readFile((await calendar.path())!,'utf8');
    expect(ics).toContain('BEGIN:VCALENDAR');expect(ics).not.toContain('Anna');expect(ics).not.toContain('ATTENDEE');
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await change.locator('[name=command]').selectOption('CANCEL');await change.locator('[name=reason]').selectOption('RESCHEDULE');await change.locator('[name=confirmed]').check();
    await change.getByRole('button',{name:'Zapisz rozmowę'}).click();
    await expect(page.locator('#f-interview-list').getByText('Anulowane',{exact:true})).toBeVisible();
    expect(errors).toEqual([]); expect(retired).toEqual([]);
  } finally { try { if (!page.isClosed()) { await page.screenshot({path:info.outputPath('final-state.png'),fullPage:true}); await page.goto('about:blank'); } } finally { await f.close(); } }
});

test('clarification workspace shares only structured declarations and keeps profile snapshot unchanged',async({page})=>{
  const f=await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('ClarifyEmployer'),candidate=await f.user('ClarifyCandidate');
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Rozmowa o kompetencjach'},201);
    f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',expectedVersion:0,availability:{kind:'IMMEDIATE'}});
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',offerInput(employer.id),201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    const preview=await f.request<{confirmationToken:string}>('/api/faro/profile/preview-confirmation',candidate.cookie);
    const p=await f.request<{id:string}>(`/api/faro/offers/${offer.id}/interest`,candidate.cookie,'POST',{offerVersion:1,projectionConfirmed:true,confirmationToken:preview.confirmationToken,idempotencyKey:'browser-clarify-interest'},201);
    await login(page,f.base,employer.email);await page.goto(`${f.base}/#processes/${p.id}`);
    const command=page.locator('[data-form=process-command]');
    await command.locator('[name=command]').selectOption('CLARIFY');
    await command.locator('[name=questionTopic]').selectOption('REQUIREMENT');
    await command.locator('[name=questionRequirementId]').selectOption('req-customer');
    await command.locator('[name=dueAt]').fill('2099-01-01T12:00');await command.locator('[name=confirmed]').check();
    await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('Pytanie do kandydata',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);await page.goto(`${f.base}/#processes/${p.id}`);
    await expect(command.locator('[name=answer]')).toHaveCount(0);
    await command.locator('[name=command]').selectOption('ANSWER');await command.locator('[name=responseKind]').selectOption('DECLARE_SKILL');
    await command.locator('[name=level]').selectOption('INDEPENDENT');await command.locator('[name=source]').selectOption('WORK');
    await command.locator('[name=quantity]').fill('12');await command.locator('[name=unit]').selectOption('MONTHS');await command.locator('[name=confirmed]').check();
    await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-timeline')).toContainText('Deklaruję kompetencję');
    const view=await f.request<{projection:{skillClaims:unknown[]};stage:string}>(`/api/faro/processes/${p.id}`,employer.cookie);
    expect(view.projection.skillClaims).toHaveLength(0);expect(view.stage).toBe('AWAITING_EMPLOYER');
    await command.locator('[name=command]').selectOption('WITHDRAW');await command.locator('[name=confirmed]').check();await command.getByRole('button',{name:'Zapisz działanie'}).click();
    await expect(page.locator('.f-detail').getByText('Wycofane',{exact:true})).toBeVisible();
    await page.goto(`${f.base}/#offers/${offer.id}`);await page.getByRole('button',{name:'Zgłoś ponownie zainteresowanie'}).click();
    const dialog=page.getByRole('dialog');await dialog.locator('[name=projectionConfirmed]').check();await dialog.locator('[name=renewalConfirmed]').check();
    await dialog.getByRole('button',{name:'Zgłoś zainteresowanie',exact:true}).click();
    await expect(page.getByRole('link',{name:'Otwórz poprzedni proces'})).toBeVisible();
    const history=await f.request<{processes:Array<{id:string;previousInterestId:string|null}>}>('/api/faro/processes',candidate.cookie);
    expect(history.processes).toHaveLength(2);expect(history.processes.find(process=>process.id!==p.id)?.previousInterestId).toBe(p.id);
  } finally {await page.goto('about:blank');await f.close();}
});

test('case workspace supports private explanations from both sides, independent review and candidate appeal',async({page})=>{
  const f=await faroFixture();f.app.config.appOrigin=f.base;
  try {
    const employer=await f.user('CaseBrowserEmployer'),candidate=await f.user('CaseBrowserCandidate'),admin=await f.user('CaseBrowserModerator');
    f.app.db.db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(admin.id);
    const org=await f.request<{id:string}>('/api/faro/organizations',employer.cookie,'POST',{name:'Sprawa po rozmowie'},201);
    f.app.db.db.prepare("UPDATE faro_organizations SET verification='VERIFIED' WHERE id=?").run(org.id);
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',expectedVersion:0,availability:{kind:'IMMEDIATE'}});
    const offer=await f.request<{id:string}>(`/api/faro/organizations/${org.id}/offers`,employer.cookie,'POST',offerInput(employer.id),201);
    await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'REVIEW',expectedVersion:1});await f.request(`/api/faro/offers/${offer.id}/lifecycle`,employer.cookie,'POST',{action:'PUBLISH',expectedVersion:2,confirmed:true});
    const preview=await f.request<{confirmationToken:string}>('/api/faro/profile/preview-confirmation',candidate.cookie);
    const p=await f.request<{id:string}>(`/api/faro/offers/${offer.id}/interest`,candidate.cookie,'POST',{offerVersion:1,projectionConfirmed:true,confirmationToken:preview.confirmationToken,idempotencyKey:'case-browser-interest'},201);
    await f.request(`/api/faro/processes/${p.id}/commands`,employer.cookie,'POST',{command:'ADVANCE',nextAction:'Uzgodnijmy rozmowę',dueAt:new Date(Date.now()+86400000).toISOString(),expectedVersion:1,idempotencyKey:'case-browser-advance'});
    // A controlled fixture clock reaches the meeting outcome without a wall-clock sleep.
    const now=Date.now(),interviews=new InterviewService(f.app.db,()=>new Date(now-3*3600000));
    const meeting=interviews.propose(employer.id,p.id,{startsAt:new Date(now-2*3600000).toISOString(),endsAt:new Date(now-3600000).toISOString(),confirmBy:new Date(now-2.5*3600000).toISOString(),timezone:'Europe/Warsaw',location:'Online',confirmed:true,expectedVersion:2,idempotencyKey:'case-browser-propose'});
    interviews.change(candidate.id,meeting.id,{command:'CONFIRM',confirmed:true,expectedVersion:1,processVersion:3,idempotencyKey:'case-browser-confirm'});
    await f.request(`/api/faro/interviews/${meeting.id}`,employer.cookie,'POST',{command:'DISPUTE',reason:'NO_SHOW',confirmed:true,expectedVersion:2,processVersion:4,idempotencyKey:'case-browser-dispute'});
    await login(page,f.base,candidate.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    const explanation=page.locator('[data-form=case-explain]');await explanation.locator('[name=statement]').fill('Prywatna informacja medyczna kandydata.');await explanation.getByRole('button',{name:'Przekaż wyjaśnienie'}).click();
    await expect(page.locator('#f-content')).toContainText('Prywatna informacja medyczna kandydata.');
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,employer.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).not.toContainText('informacja medyczna');
    await explanation.locator('[name=statement]').fill('Prywatne wyjaśnienie firmy dotyczące połączenia.');await explanation.getByRole('button',{name:'Przekaż wyjaśnienie'}).click();
    await expect(page.locator('#f-content')).toContainText('Prywatne wyjaśnienie firmy');
    await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,admin.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).toContainText('informacja medyczna');await expect(page.locator('#f-content')).toContainText('wyjaśnienie firmy');
    const review=page.locator('[data-form=case-review]');await review.locator('[name=state]').selectOption('EVIDENCE_REVIEW');await review.locator('[name=decision]').fill('Prywatna notatka moderatora o sprawdzeniu materiału.');await review.locator('[name=reviewAt]').fill('2099-01-03T12:00');await review.locator('[name=explanationDueAt]').fill('2099-01-02T12:00');await review.getByRole('button',{name:'Zapisz przegląd'}).click();
    await expect(page.locator('.f-chip')).toHaveText('EVIDENCE_REVIEW');
    await review.locator('[name=state]').selectOption('NO_ACTION');await review.locator('[name=decision]').fill('Prywatna notatka moderatora o braku naruszenia.');await review.locator('[name=decisionCode]').selectOption('NO_VIOLATION_CONFIRMED');await review.locator('[name=reviewAt]').fill('2099-01-03T12:00');await review.getByRole('button',{name:'Zapisz przegląd'}).click();
    await expect(page.locator('.f-chip')).toHaveText('NO_ACTION');await page.getByRole('button',{name:'Wyloguj',exact:true}).click();await login(page,f.base,candidate.email);await page.getByRole('link',{name:'Zgłoszenia',exact:true}).click();
    await expect(page.locator('#f-content')).not.toContainText('notatka moderatora');
    const appeal=page.locator('[data-form=appeal]');await appeal.locator('[name=statement]').fill('Proszę o ponowne prywatne sprawdzenie rozbieżności.');await appeal.getByRole('button',{name:'Zapisz odwołanie'}).click();await expect(page.locator('.f-chip')).toHaveText('APPEAL');
  }finally{await page.goto('about:blank');await f.close();}
});

test('privacy workspace exports own data and requires reauthentication before erasure',async({page})=>{
  const f=await faroFixture(); f.app.config.appOrigin=f.base;
  try{
    const candidate=await f.user('PrivacyBrowser');
    await f.request('/api/faro/profile',candidate.cookie,'PUT',{firstName:'Anna',availability:{kind:'IMMEDIATE'},expectedVersion:0});
    await login(page,f.base,candidate.email);
    await page.getByRole('link',{name:'Prywatność',exact:true}).click();
    const downloaded=page.waitForEvent('download');
    await page.getByRole('button',{name:'Pobierz moje dane'}).click();
    const file=await downloaded;
    const payload=JSON.parse(await readFile((await file.path())!,'utf8')) as {faro:{faro_profiles:Array<{first_name:string}>}};
    expect(payload.faro.faro_profiles[0]!.first_name).toBe('Anna');
    const deletion=page.locator('[data-form=delete-account]');
    await deletion.locator('[name=confirmation]').fill('USUŃ KONTO');
    await deletion.locator('[name=password]').fill('BledneHaslo123');
    await deletion.locator('[name=confirmed]').check();
    await deletion.getByRole('button',{name:'Usuń moje konto'}).click();
    await expect(deletion.locator('.f-form-message')).toContainText('poprawne aktualne hasło');
    await expect(page.locator('.f-brand')).toBeVisible();
    await deletion.locator('[name=password]').fill('Bezpieczne123');
    await deletion.getByRole('button',{name:'Usuń moje konto'}).click();
    await expect(page.locator('#loginForm')).toBeVisible();
    await expect(page.locator('#authMessage')).toHaveText('Konto i dane zostały usunięte.');
    await f.request('/api/me',candidate.cookie,'GET',undefined,401);
  }finally{if(!page.isClosed())await page.goto('about:blank'); await f.close();}
});
