import { randomUUID } from 'node:crypto';
import { HttpError } from '../http.js';
import { text,choice,integer,date } from './validation.js';
import { runCommandOnce } from './commandJournal.js';
import { caseReadQuery,caseFromRows,caseParticipantOwned,caseInvolvedOwned,moderatorRoleQuery,moderationReadAudit,type CaseRow,type TrustReadDatabase } from './trustReadModel.js';
import { processReadQuery,processFromRows } from './processReadModel.js';
import { offerReadQuery,offerFromRows } from './offerReadModel.js';
import { processRecruiterReadQuery,processEventQueries } from './interestWriteModel.js';
import { tickNotificationQuery } from './trustTickModel.js';
export function caseReportPlan(userId:string,processId:string,orgId:string,body:Record<string,unknown>,asOf:string){const id=randomUUID();return {ack:{id,state:'OPEN'},queries:[{text:'INSERT INTO faro_cases(id,organization_id,process_id,reporter_id,kind,statement,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',values:[id,orgId,processId,userId,choice(body.kind,['CV_REQUEST','DISCRIMINATION','SCAM','PROCESS','ASSESSMENT_ABUSE','TECHNICAL_ISSUE'] as const),text(body.statement,2000,10),asOf]},moderationReadAudit(userId,'PRIVATE_REPORT_CREATED',id,asOf)]};}
export function caseExplanationPlan(userId:string,row:CaseRow,participant:'CANDIDATE'|'EMPLOYER',body:Record<string,unknown>,asOf:string){
 if(!['NO_SHOW_CASE','INTERVIEW_DISCREPANCY'].includes(row.kind)||!['OPEN','EVIDENCE_REVIEW','APPEAL'].includes(row.state))throw new HttpError(409,'Wyjaśnienie nie jest teraz dostępne.');
 if(integer(body.expectedVersion,1)!==row.revision)throw new HttpError(409,'Odśwież sprawę.','VERSION_CONFLICT');
 const explanationId=randomUUID();return {explanationId,ack:{id:row.id,revision:row.revision+1},queries:[{text:'INSERT INTO faro_case_explanations(id,case_id,user_id,participant,statement,created_at) VALUES($1,$2,$3,$4,$5,$6)',values:[explanationId,row.id,userId,participant,text(body.statement,2000,10),asOf]},{text:'UPDATE faro_cases SET revision=revision+1 WHERE id=$1',values:[row.id]},moderationReadAudit(userId,'PRIVATE_CASE_EXPLANATION',row.id,asOf)]};
}
export function caseAppealPlan(userId:string,row:CaseRow,body:Record<string,unknown>,asOf:string){
 if(integer(body.expectedVersion,1)!==row.revision)throw new HttpError(409,'Odśwież sprawę.','VERSION_CONFLICT');
 if(!['ACTION','NO_ACTION'].includes(row.state))throw new HttpError(409,'Odwołanie nie jest teraz dostępne.');
 return {ack:{id:row.id,state:'APPEAL',revision:row.revision+1},queries:[{text:"UPDATE faro_cases SET state='APPEAL',appeal=$1,appeal_by=$2,revision=revision+1 WHERE id=$3",values:[text(body.statement,2000,10),userId,row.id]},moderationReadAudit(userId,'MODERATION_APPEALED',row.id,asOf)]};
}
export async function notifyCaseModeratorsOwned(database:TrustReadDatabase,id:string,message:string,key:string,asOf:string){const recipients=(await database.readBatch([{text:"SELECT id FROM users WHERE role='ADMIN'",values:[]}]))[0]??[];for(const recipient of recipients){const query=tickNotificationQuery(recipient.id as string,'case',id,message,key,asOf);await database.query(query.text,query.values);}}
export async function caseProcessEventOwned(database:TrustReadDatabase,userId:string,row:CaseRow,data:Record<string,unknown>,asOf:string){if(row.process_id){const process=processFromRows((await database.readBatch([processReadQuery(row.process_id)]))[0]??[]),recipients=(await database.readBatch([processRecruiterReadQuery(process.offer_id)]))[0]??[];for(const query of processEventQueries(process,userId,'MODERATION_CASE_UPDATED',data,recipients,asOf))await database.query(query.text,query.values);}}
export async function reportPrivateCase(database:TrustReadDatabase,userId:string,processId:string,body:Record<string,unknown>,asOf:string,authorize:()=>void|Promise<void>){let orgId:string;return runCommandOnce(database,userId,body.idempotencyKey,{...body,processId,operation:'CASE_REPORT'},asOf,async()=>{await authorize();const process=processFromRows((await database.readBatch([processReadQuery(processId)]))[0]??[]);orgId=offerFromRows((await database.readBatch([offerReadQuery(process.offer_id)]))[0]??[]).organizationId;await caseParticipantOwned(database,userId,{process_id:processId,organization_id:orgId} as CaseRow);},async()=>{const plan=caseReportPlan(userId,processId,orgId,body,asOf);for(const query of plan.queries)await database.query(query.text,query.values);await notifyCaseModeratorsOwned(database,plan.ack.id,'Nowe prywatne zgłoszenie wymaga przeglądu.',`case:${plan.ack.id}:report`,asOf);return plan.ack;});}
export async function explainPrivateCase(database:TrustReadDatabase,userId:string,id:string,body:Record<string,unknown>,asOf:string,authorize:()=>void|Promise<void>){let row:CaseRow,participant:'CANDIDATE'|'EMPLOYER';return runCommandOnce(database,userId,body.idempotencyKey,{...body,id,operation:'CASE_EXPLAIN'},asOf,async()=>{await authorize();row=caseFromRows((await database.readBatch([caseReadQuery(id)]))[0]??[]);participant=await caseParticipantOwned(database,userId,row);},async()=>{const plan=caseExplanationPlan(userId,row,participant,body,asOf);for(const query of plan.queries)await database.query(query.text,query.values);await notifyCaseModeratorsOwned(database,id,'Wpłynęło prywatne wyjaśnienie do sprawy.',`case:${id}:explanation:${plan.explanationId}`,asOf);return plan.ack;});}
export async function appealPrivateCase(database:TrustReadDatabase,userId:string,id:string,body:Record<string,unknown>,asOf:string,authorize:()=>void|Promise<void>){let row:CaseRow;return runCommandOnce(database,userId,body.idempotencyKey,{...body,id,operation:'CASE_APPEAL'},asOf,async()=>{await authorize();row=caseFromRows((await database.readBatch([caseReadQuery(id)]))[0]??[]);if(row.reporter_id!==userId)await caseParticipantOwned(database,userId,row);},async()=>{const plan=caseAppealPlan(userId,row,body,asOf);for(const query of plan.queries)await database.query(query.text,query.values);await notifyCaseModeratorsOwned(database,id,'Wpłynęło prywatne odwołanie od decyzji.',`case:${id}:appeal:${row.revision+1}`,asOf);await caseProcessEventOwned(database,userId,row,{caseId:id,state:'APPEAL'},asOf);return plan.ack;});}

export function caseReviewPlan(userId:string,row:CaseRow,body:Record<string,unknown>,sides:number,candidateId:string|null,asOf:string){
 if(integer(body.expectedVersion,1)!==row.revision)throw new HttpError(409,'Odśwież sprawę.','VERSION_CONFLICT');
 const target=choice(body.state,['EVIDENCE_REVIEW','ACTION','NO_ACTION','RESOLVED'] as const),valid:Record<string,string[]>={OPEN:['EVIDENCE_REVIEW'],EVIDENCE_REVIEW:['ACTION','NO_ACTION'],APPEAL:['RESOLVED'],ACTION:['RESOLVED'],NO_ACTION:['RESOLVED']};
 if(!valid[row.state]?.includes(target))throw new HttpError(409,'Niedozwolony stan sprawy.');
 const decision=text(body.decision,1500,10),reviewAt=date(body.reviewAt),publicReason=target==='EVIDENCE_REVIEW'?null:choice(body.decisionCode,['PROCESS_VIOLATION_CONFIRMED','INSUFFICIENT_EVIDENCE','TECHNICAL_ISSUE','NO_VIOLATION_CONFIRMED','CASE_RESOLVED'] as const),bilateral=['NO_SHOW_CASE','INTERVIEW_DISCREPANCY'].includes(row.kind);let explanationDue=row.explanation_due_at;
 if(bilateral&&target==='EVIDENCE_REVIEW'){explanationDue=date(body.explanationDueAt);if(explanationDue<=asOf)throw new HttpError(400,'Termin na wyjaśnienia musi być w przyszłości.');}
 if(bilateral&&['ACTION','NO_ACTION'].includes(target)&&sides<2&&(!explanationDue||explanationDue>asOf))throw new HttpError(409,'Najpierw wyjaśnienia obu stron albo upływ jawnego terminu.','EXPLANATION_WINDOW_OPEN');
 if(target==='ACTION'&&body.restrict===true&&row.kind==='NO_SHOW_CASE'&&(!candidateId||row.reporter_id!==candidateId))throw new HttpError(409,'Sprawa dotycząca kandydata nie może ograniczyć organizacji. Ograniczenia kandydata wymagają odrębnej zatwierdzonej polityki.','RESTRICTION_SCOPE');
 const queries:Array<{text:string;values:readonly (string|number|null)[]}>=[{text:'UPDATE faro_cases SET state=$1,decision=$2,public_reason=$3,review_at=$4,explanation_due_at=$5,revision=revision+1 WHERE id=$6',values:[target,decision,publicReason,reviewAt,explanationDue,row.id]}];let restrictionId:string|null=null;
 if(target==='ACTION'&&body.restrict===true){const condition=text(body.restorationCondition,1000,10);if(reviewAt<=asOf)throw new HttpError(400,'Wybierz przyszły termin przeglądu ograniczenia.');restrictionId=randomUUID();queries.push({text:'INSERT INTO faro_restrictions(id,organization_id,source_case_id,source_reporter_id,source_candidate_id,reason_code,restoration_condition,created_at,review_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',values:[restrictionId,row.organization_id,row.id,row.reporter_id,candidateId,publicReason,condition,asOf,reviewAt]},{text:"UPDATE faro_organizations SET verification='RESTRICTED' WHERE id=$1",values:[row.organization_id]},{text:"UPDATE faro_offers SET status='PAUSED',revision=revision+1 WHERE organization_id=$1 AND status='PUBLISHED'",values:[row.organization_id]});}
 queries.push(moderationReadAudit(userId,'MODERATION_REVIEWED',row.id,asOf));return {ack:{id:row.id,state:target,revision:row.revision+1},queries,restrictionId,event:{caseId:row.id,state:target,explanationDueAt:explanationDue}};
}
export async function reviewPrivateCase(database:TrustReadDatabase,userId:string,id:string,body:Record<string,unknown>,asOf:string,authorize:()=>void|Promise<void>){let row:CaseRow;return runCommandOnce(database,userId,body.idempotencyKey,{...body,id,operation:'CASE_REVIEW'},asOf,async()=>{await authorize();if(!(await database.readBatch([moderatorRoleQuery(userId)]))[0]?.length)throw new HttpError(403,'Wymagany moderator.');row=caseFromRows((await database.readBatch([caseReadQuery(id)]))[0]??[]);if(await caseInvolvedOwned(database,userId,row))throw new HttpError(409,'Sprawę musi rozpatrzyć moderator niezwiązany z jej stronami.','MODERATION_CONFLICT');},async()=>{
 const sides=Number((await database.readBatch([{text:'SELECT COUNT(DISTINCT participant) n FROM faro_case_explanations WHERE case_id=$1',values:[id]}]))[0]?.[0]?.n??0),candidateId=row.process_id?processFromRows((await database.readBatch([processReadQuery(row.process_id)]))[0]??[]).candidate_id:null,plan=caseReviewPlan(userId,row,body,sides,candidateId,asOf);
 for(const query of plan.queries)await database.query(query.text,query.values);
 if(plan.restrictionId){const recipients=(await database.readBatch([{text:"SELECT user_id FROM faro_members WHERE organization_id=$1 AND active=1 AND role IN ('OWNER','ADMIN')",values:[row.organization_id]}]))[0]??[];for(const recipient of recipients){const query=tickNotificationQuery(recipient.user_id as string,'organization',row.organization_id,'Zmieniono stan ograniczenia organizacji. Sprawdź zakres i ręczny przegląd.',`restriction:${plan.restrictionId}:1`,asOf);await database.query(query.text,query.values);}}
 await caseProcessEventOwned(database,userId,row,plan.event,asOf);return plan.ack;
});}
