import { createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual } from 'node:crypto';
import type { AppConfig } from '../config.js';
import type { UserRecord } from '../store.js';
import { verifyPassword,MAX_PASSWORD_LENGTH } from '../auth.js';
import { HttpError } from '../http.js';
import { FaroStore } from './base.js';
import type { JobDatabase } from '../db.js';
interface MfaRow {active_cipher:string|null;pending_cipher:string|null;pending_until:string|null;last_counter:number;activated_at:string|null;}
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32(buffer:Buffer) {let bits=0,value=0,result='';for(const byte of buffer){value=(value<<8)|byte;bits+=8;while(bits>=5){bits-=5;result+=alphabet[(value>>>bits)&31];}}if(bits)result+=alphabet[(value<<(5-bits))&31];return result;}
/** RFC6238/HOTP dynamic truncation; 64-bit counter, explicit algorithm/digits for published vectors. */
export function totp(secret:Buffer,counter:number,digits=6,algorithm='sha1') {
  const moving=Buffer.alloc(8);moving.writeBigUInt64BE(BigInt(counter));const hash=createHmac(algorithm,secret).update(moving).digest(),offset=hash.at(-1)!&15;
  return String((hash.readUInt32BE(offset)&0x7fffffff)%10**digits).padStart(digits,'0');
}
export class MfaService extends FaroStore {
  constructor(db:JobDatabase,readonly config:AppConfig,clock:()=>Date=()=>new Date()){super(db,clock);}
  row(userId:string){return this.db.prepare('SELECT * FROM faro_mfa WHERE user_id=?').get(userId) as unknown as MfaRow|undefined;}
  privileged(user:UserRecord){return user.role==='ADMIN'||Boolean(this.db.prepare("SELECT 1 FROM faro_members WHERE user_id=? AND active=1 AND role IN ('OWNER','ADMIN','RECRUITER','HIRING_MANAGER')").get(user.id));}
  verified(tokenHash:string){return Boolean(this.db.prepare('SELECT 1 FROM faro_mfa_sessions v JOIN sessions s ON s.token_hash=v.token_hash WHERE v.token_hash=? AND v.verified_until>? AND s.expires_at>?').get(tokenHash,this.now(),this.now()));}
  required(user:UserRecord){return Boolean(this.row(user.id)?.active_cipher)||(this.config.faroRequirePrivilegedMfa&&this.privileged(user));}
  status(user:UserRecord,tokenHash:string){const row=this.row(user.id);return {configured:Boolean(this.config.faroMfaEncryptionKey),enabled:Boolean(row?.active_cipher),required:this.required(user),verified:this.verified(tokenHash),pending:Boolean(row?.pending_until&&row.pending_until>this.now()),recoveryRemaining:Number(this.db.prepare('SELECT COUNT(*) n FROM faro_mfa_recovery WHERE user_id=? AND used_at IS NULL').get(user.id)!.n)};}
  assertAccess(user:UserRecord,tokenHash:string){if(this.required(user)&&!this.verified(tokenHash))throw new HttpError(403,'Potwierdź dostęp drugim składnikiem.','MFA_REQUIRED');}
  private actor(user:UserRecord,tokenHash:string){if(!this.db.prepare('SELECT 1 FROM sessions WHERE user_id=? AND token_hash=? AND expires_at>?').get(user.id,tokenHash,this.now()))throw new HttpError(401,'Zaloguj się, aby kontynuować.','UNAUTHENTICATED');}
  private key(){if(!this.config.faroMfaEncryptionKey)throw new HttpError(503,'MFA wymaga skonfigurowanego chronionego klucza serwera.','MFA_UNAVAILABLE');return Buffer.from(this.config.faroMfaEncryptionKey,'hex');}
  private encrypt(userId:string,secret:Buffer){const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key(),nonce);cipher.setAAD(Buffer.from(`faro-mfa-v1:${userId}`));const payload=Buffer.concat([cipher.update(secret),cipher.final()]);return [nonce,cipher.getAuthTag(),payload].map(b=>b.toString('hex')).join('.');}
  private decrypt(userId:string,value:string){const [nonce,tag,payload]=value.split('.');try{const cipher=createDecipheriv('aes-256-gcm',this.key(),Buffer.from(nonce!,'hex'));cipher.setAAD(Buffer.from(`faro-mfa-v1:${userId}`));cipher.setAuthTag(Buffer.from(tag!,'hex'));return Buffer.concat([cipher.update(Buffer.from(payload!,'hex')),cipher.final()]);}catch(error){if(error instanceof HttpError)throw error;throw new HttpError(503,'Nie można odczytać chronionego sekretu MFA.','MFA_UNAVAILABLE');}}
  private limit(userId:string){const row=this.db.prepare('SELECT failures,window_start FROM faro_mfa_limits WHERE user_id=?').get(userId) as {failures:number;window_start:string}|undefined;if(row&&row.failures>=5&&Date.parse(row.window_start)+600000>this.clock().getTime())throw new HttpError(429,'Zbyt wiele nieudanych potwierdzeń. Spróbuj po 10 minutach.','MFA_RATE_LIMITED');}
  private fail(userId:string):never {
    const cutoff=new Date(this.clock().getTime()-600000).toISOString();
    this.db.prepare('INSERT INTO faro_mfa_limits(user_id,failures,window_start) VALUES(?,1,?) ON CONFLICT(user_id) DO UPDATE SET failures=CASE WHEN window_start<=? THEN 1 ELSE failures+1 END,window_start=CASE WHEN window_start<=? THEN excluded.window_start ELSE window_start END').run(userId,this.now(),cutoff,cutoff);
    this.audit(userId,'MFA_CONFIRMATION_FAILED',userId);
    throw new HttpError(401,'Nieprawidłowe potwierdzenie dostępu.','REAUTH_FAILED');
  }
  private password(user:UserRecord,password:unknown){this.limit(user.id);if(typeof password!=='string'||password.length>MAX_PASSWORD_LENGTH||!verifyPassword(password,user.passwordHash))this.fail(user.id);}
  private counter(userId:string,cipher:string,code:unknown,last=-1){this.limit(userId);if(typeof code!=='string'||!/^\d{6}$/.test(code))return this.fail(userId);const secret=this.decrypt(userId,cipher),now=Math.floor(this.clock().getTime()/30000);for(const counter of [now,now-1,now+1])if(counter>=0&&counter>last&&timingSafeEqual(Buffer.from(code),Buffer.from(totp(secret,counter))))return counter;return this.fail(userId);}
  private grant(tokenHash:string){this.db.prepare('INSERT INTO faro_mfa_sessions(token_hash,verified_until) VALUES(?,?) ON CONFLICT(token_hash) DO UPDATE SET verified_until=excluded.verified_until').run(tokenHash,new Date(this.clock().getTime()+300000).toISOString());}
  private success(userId:string){this.db.prepare('DELETE FROM faro_mfa_limits WHERE user_id=?').run(userId);}
  setup(user:UserRecord,tokenHash:string,body:Record<string,unknown>){this.actor(user,tokenHash);this.key();this.password(user,body.password);if(this.row(user.id)?.active_cipher&&!this.verified(tokenHash))throw new HttpError(403,'Najpierw potwierdź dotychczasowy drugi składnik.','MFA_REQUIRED');const secret=randomBytes(20),cipher=this.encrypt(user.id,secret),until=new Date(this.clock().getTime()+300000).toISOString();this.transaction(()=>{this.db.prepare('INSERT INTO faro_mfa(user_id,pending_cipher,pending_until) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET pending_cipher=excluded.pending_cipher,pending_until=excluded.pending_until').run(user.id,cipher,until);this.audit(user.id,'MFA_SETUP_STARTED',user.id);});return {secret:base32(secret),expiresAt:until,algorithm:'SHA1',digits:6,period:30};}
  confirm(user:UserRecord,tokenHash:string,body:Record<string,unknown>){this.actor(user,tokenHash);const row=this.row(user.id);if(!row?.pending_cipher||!row.pending_until||row.pending_until<=this.now())throw new HttpError(409,'Rozpocznij ponownie konfigurację MFA.','MFA_SETUP_EXPIRED');const counter=this.counter(user.id,row.pending_cipher,body.code),codes=Array.from({length:8},()=>randomBytes(16).toString('hex'));this.transaction(()=>{this.limit(user.id);const current=this.row(user.id);if(current?.pending_cipher!==row.pending_cipher)throw new HttpError(409,'Konfiguracja zmieniła się.');this.db.prepare('UPDATE faro_mfa SET active_cipher=pending_cipher,pending_cipher=NULL,pending_until=NULL,last_counter=?,activated_at=? WHERE user_id=?').run(counter,this.now(),user.id);this.db.prepare('DELETE FROM faro_mfa_recovery WHERE user_id=?').run(user.id);for(const code of codes)this.db.prepare('INSERT INTO faro_mfa_recovery(user_id,code_hash) VALUES(?,?)').run(user.id,this.recoveryHash(user.id,code));this.db.prepare('DELETE FROM sessions WHERE user_id=? AND token_hash<>?').run(user.id,tokenHash);this.grant(tokenHash);this.success(user.id);this.audit(user.id,'MFA_ENABLED',user.id);});return {recoveryCodes:codes};}
  verify(user:UserRecord,tokenHash:string,body:Record<string,unknown>){this.actor(user,tokenHash);const row=this.row(user.id);if(!row?.active_cipher)throw new HttpError(409,'Najpierw skonfiguruj MFA.','MFA_ENROLLMENT_REQUIRED');const counter=this.counter(user.id,row.active_cipher,body.code,row.last_counter);this.transaction(()=>{this.limit(user.id);const changed=this.db.prepare('UPDATE faro_mfa SET last_counter=? WHERE user_id=? AND active_cipher=? AND last_counter<?').run(counter,user.id,row.active_cipher,counter);if(changed.changes!==1)throw new HttpError(409,'Kod został już wykorzystany.','MFA_CODE_REPLAY');this.grant(tokenHash);this.success(user.id);this.audit(user.id,'MFA_VERIFIED',user.id);});return {ok:true};}
  private recoveryHash(userId:string,code:string){return createHash('sha256').update(`faro-mfa-recovery-v1:${userId}:${code}`).digest('hex');}
  recover(user:UserRecord,tokenHash:string,body:Record<string,unknown>){this.actor(user,tokenHash);this.password(user,body.password);if(typeof body.code!=='string'||!/^\w{32}$/.test(body.code))return this.fail(user.id);const hash=this.recoveryHash(user.id,body.code),row=this.db.prepare('SELECT used_at FROM faro_mfa_recovery WHERE user_id=? AND code_hash=?').get(user.id,hash);if(!row||row.used_at!==null)return this.fail(user.id);this.transaction(()=>{this.limit(user.id);const changed=this.db.prepare('UPDATE faro_mfa_recovery SET used_at=? WHERE user_id=? AND code_hash=? AND used_at IS NULL').run(this.now(),user.id,hash);if(changed.changes!==1)throw new HttpError(409,'Kod odzyskiwania został już wykorzystany.');this.db.prepare('DELETE FROM sessions WHERE user_id=? AND token_hash<>?').run(user.id,tokenHash);this.grant(tokenHash);this.success(user.id);this.audit(user.id,'MFA_RECOVERY_USED',user.id);});return {ok:true};}
}
