import type { Profile, Skill, Offer, Process, Economics, Attempt } from './faroTypes.js';
import { esc, label, salary, date, money, chip, form, select, input, area, check, button, skillSelect, claimFields, practiceFields, projection } from './faroUi.js';
export function profileView(p: Profile, skills: Skill[]) {
  const skill = (id: string) => skills.find(s => s.id === id)?.label ?? id;
  return `<div class="f-page-heading"><p class="f-kicker">TWÓJ KIERUNEK</p><h1>Umiejętności otwierają możliwości.</h1><p>Opisujesz czynności i naukę. Samodzielnie potwierdzasz każdą kompetencję.</p></div>
  <div class="f-grid"><section class="f-card"><h2>Podstawowe informacje</h2>${form('profile', input('firstName', 'Imię', p.firstName, 'text', 'required maxlength="60" autocomplete="given-name"') + input('phone', 'Prywatny telefon — udostępniasz osobno', p.phone, 'tel', 'maxlength="20"') + select('availability', 'Dostępność', ['UNKNOWN','IMMEDIATE','AFTER_PERIOD','ON_DATE'], p.availability.kind) + input('availabilityValue', 'Data RRRR-MM-DD lub liczba dni', p.availability.value, 'text', '') + `<input type="hidden" name="version" value="${p.version}">`, 'Zapisz profil')}${button('preview', 'Zobacz, co zobaczy pracodawca')}</section>
  <section class="f-card"><h2>Co potrafię</h2>${p.claims.map(c => `<div class="f-row"><strong>${esc(skill(c.skillId))}</strong><p>${esc(label(c.level))} · ${esc(label(c.source))}</p>${chip(label(c.verification))} ${button('revoke-claim', 'Usuń deklarację', c.id)}</div>`).join('') || '<p class="f-muted">Możesz zacząć bez doświadczenia.</p>'}<details><summary>Dodaj kompetencję</summary>${form('claim', skillSelect(skills) + claimFields(), 'Zapisz deklarację')}</details></section>
  ${['SELF_DEVELOPING','WANTS_TO_LEARN'].map(mode => `<section class="f-card"><h2>${mode === 'SELF_DEVELOPING' ? 'Co rozwijam samodzielnie' : 'Czego chcę się nauczyć'}</h2>${p.learning.filter(l => l.mode === mode).map(l => chip(skill(l.skillId))).join('') || '<p class="f-muted">Wybierz własny kierunek.</p>'}${form('learning', `<input type="hidden" name="mode" value="${mode}">` + skillSelect(skills) + practiceFields(), 'Zapisz kierunek')}</section>`).join('')}
  <section class="f-card f-wide"><h2>Mam doświadczenie w…</h2><p>Opisz konkretne czynności. Opis jest prywatny; pracodawca zobaczy wyłącznie potwierdzone kompetencje.</p>${p.activities.map(a => `<p class="f-row">${esc(a.description)}</p>`).join('')}${form('activity', area('description', 'Co robiłeś lub robiłaś?', '', 'required maxlength="3000" placeholder="np. pomagałem klientom na stacji, obsługiwałem kasę"') + select('source', 'Źródło doświadczenia', ['WORK','SELF_LEARNING','HOBBY','SCHOOL','VOLUNTEERING']), 'Zapisz i sprawdź propozycje')}
  <p class="f-muted">Propozycje powstają obecnie według lokalnych reguł. Nie są weryfikacją kompetencji ani wynikiem działającego modelu AI.</p>${p.proposals.filter(p => p.status === 'PENDING').map(p => `<details class="f-row"><summary>${esc(skill(p.skill_id))} — potwierdź lub odrzuć</summary><p>${esc(p.rationale)}</p>${form('proposal', claimFields(), 'Potwierdź kompetencję', p.id)}${button('reject-proposal', 'To nie opisuje mojej praktyki', p.id)}</details>`).join('')}</section></div>`;
}
export function offerForm(skills: Skill[], userId: string, offer?: Offer) {
  const d = offer?.data, s = d?.salary[0];
  const reqs = d?.requirements ?? [];
  return `<section class="f-card"><h2>${offer ? 'Nowa wersja oferty' : 'Nowa oferta Faro'}</h2><p>Wynagrodzenie i warunki są jawne. Zapis tworzy szkic wymagający review.</p>${form('offer',
    input('role', 'Rola', d?.role, 'text', 'required maxlength="150"') + input('location', 'Lokalizacja', d?.location, 'text', 'required maxlength="200"') + area('responsibilities', 'Zadania — jedno w wierszu', d?.responsibilities.join('\n')) +
    select('workModel', 'Model pracy', ['ONSITE','HYBRID','REMOTE'], d?.workModel) + input('remoteDays', 'Dni zdalne w tygodniu', d?.remoteDays ?? 0, 'number', 'required min="0" max="7"') +
    select('contract', 'Umowa', ['UOP','CIVIL','B2B'], s?.contract) + select('period', 'Okres wynagrodzenia', ['MONTH','HOUR','DAY','YEAR'], s?.period) + input('salaryMin', 'Wynagrodzenie od (PLN brutto / faktura bez VAT)', s ? s.min / 100 : '', 'number', 'required min="0.01" step="0.01"') + input('salaryMax', 'Wynagrodzenie do (PLN)', s ? s.max / 100 : '', 'number', 'required min="0.01" step="0.01"') +
    input('hoursPerPeriod', 'Liczba godzin w okresie wynagrodzenia', s?.hoursPerPeriod ?? 168, 'number', 'required min="1" max="9000"') + input('ftePercent', 'Wymiar etatu (%)', s?.ftePercent ?? 100, 'number', 'required min="1" max="100"') + input('variable', 'Składniki zmienne (opcjonalnie)', s?.variable, 'text', 'maxlength="500"') + input('hours', 'Godziny pracy', d?.hours) + input('shifts', 'Zmiany', d?.shifts) +
    select('nights', 'Praca w nocy', ['Nie określono','Tak','Nie'], d?.nights === null || !d ? 'Nie określono' : d.nights ? 'Tak' : 'Nie') + select('weekends', 'Praca w weekendy', ['Nie określono','Tak','Nie'], d?.weekends === null || !d ? 'Nie określono' : d.weekends ? 'Tak' : 'Nie') +
    `<div class="f-wide"><h3>Kompetencje</h3><p>Wybierz kategorię każdej istotnej kompetencji. „Firma nauczy” nie stanowi bariery wejścia.</p><div class="f-requirements">${skills.map(skill => { const r = reqs.find(r => r.skillId === skill.id); return `<fieldset class="f-requirement"><legend>${esc(skill.label)}</legend>${select(`kind:${skill.id}`, 'Kategoria', ['Pomijam','MUST_HAVE','NICE_TO_HAVE','WILL_TEACH'], r?.kind ?? 'Pomijam')}${select(`level:${skill.id}`, 'Poziom', ['BASICS','INDEPENDENT','FLUENT'], r?.level)}${input(`why:${skill.id}`, 'Dlaczego ta kompetencja?', r?.rationale, 'text', 'maxlength="500"')}</fieldset>`; }).join('')}</div></div>` +
    area('learningSupport', 'Możliwości nauki i wsparcie', d?.learningSupport, 'maxlength="1000"') + area('stages', 'Etapy rekrutacji — jeden w wierszu', d?.stages.join('\n')) + input('responseHours', 'Pierwsza odpowiedź w godzinach kalendarzowych', d?.responseHours ?? 48, 'number', 'required min="1" max="720"') + input('decisionHours', 'Decyzja w godzinach kalendarzowych', d?.decisionHours ?? 72, 'number', 'required min="1" max="2160"') + input('assessmentMinutes', 'Przewidywany czas assessmentu (minuty)', d?.assessmentMinutes ?? 0, 'number', 'required min="0" max="480"') + input('interviewCount', 'Liczba rozmów', d?.interviewCount ?? 1, 'number', 'required min="0" max="20"') + input('closesAt', 'Zamknięcie oferty', d?.closesAt.slice(0, 10) ?? '', 'date') + `<input type="hidden" name="recruiterId" value="${esc(d?.recruiterId ?? userId)}">`, 'Zapisz szkic', offer?.id)}</section>`;
}
export function offerDetail(o: Offer, skills: Skill[], employer: boolean, watching: boolean) {
  const d = o.data;
  return `<div class="f-detail-head"><p class="f-kicker">${esc(o.company)}</p><h2>${esc(d.role)}</h2><p class="f-salary">${d.salary.map(s => esc(salary(s))).join('<br>')}</p><div class="f-chips">${chip(label(d.workModel))}${chip(d.location)}${chip(label(o.status))}</div></div>
  <div class="f-actions">${employer ? `<a class="f-button" href="#offer-edit/${o.id}">Edytuj warunki</a><a class="f-button f-primary" href="#recruitments/${o.id}">Zgłoszenia</a><a class="f-button" href="#assessment-create/${o.id}">Assessmenty</a>` : `${button(watching ? 'unwatch' : 'watch', watching ? 'Przestań obserwować' : 'Obserwuj prywatnie', o.id)}${button('interest-preview', 'Zgłoś zainteresowanie', o.id, true)}${button('compare-add', 'Dodaj do porównania', o.id)}<a class="f-button" href="#economics/${o.id}">Koszty i netto</a>`}</div>
  ${!employer && o.acceptingInterest === false ? '<p class="f-notice">Oferta nie przyjmuje nowych zgłoszeń. Dotychczasowy proces pozostaje dostępny.</p>' : ''}
  ${employer ? `<section class="f-card"><h3>Publikacja · wersja ${o.version}</h3><p>Przed publikacją potwierdź treść. Zmiana warunków tworzy nowy szkic.</p>${form('lifecycle', select('action', 'Działanie', ({ DRAFT: ['REVIEW','CLOSE'], IN_REVIEW: ['PUBLISH','CLOSE'], PUBLISHED: ['PAUSE','RECONFIRM','CLOSE'], PAUSED: ['PUBLISH','CLOSE'], CLOSED: ['ARCHIVE'] } as Record<string,string[]>)[o.status] ?? []) + check('confirmed', 'Potwierdzam treść i aktualność warunków.'), 'Wykonaj działanie', o.id)}</section>` : `<section class="f-card"><h3>Dlaczego widzę tę ofertę?</h3><p>Oferty są uporządkowane od najnowszych. Poniżej porównujemy wymagania z Twoimi potwierdzonymi deklaracjami.</p><h3>Droga do tej pracy</h3>${(o.explanation ?? []).map(r => `<div class="f-row"><strong>${esc(skills.find(s => s.id === r.skillId)?.label ?? r.skillId)}</strong><p>${esc(label(r.kind))} · ${esc(label(r.state))}</p>${r.developing ? chip('Rozwijasz samodzielnie') : ''}${r.wantsToLearn ? chip('Chcesz się nauczyć') : ''}</div>`).join('') || '<p>Brak wymagań kompetencyjnych.</p>'}</section>`}
  <section class="f-card"><h3>Zadania i warunki</h3><ul>${d.responsibilities.map(r => `<li>${esc(r)}</li>`).join('')}</ul><dl class="f-facts"><dt>Godziny</dt><dd>${esc(d.hours)}</dd><dt>Zmiany</dt><dd>${esc(d.shifts)}</dd><dt>Weekendy</dt><dd>${d.weekends === null ? 'Nie określono' : d.weekends ? 'Tak' : 'Nie'}</dd><dt>Noce</dt><dd>${d.nights === null ? 'Nie określono' : d.nights ? 'Tak' : 'Nie'}</dd><dt>Dni zdalne</dt><dd>${d.remoteDays} / tydzień</dd></dl><h4>Nauka w firmie</h4><p>${esc(d.learningSupport) || 'Nie określono dodatkowego wsparcia.'}</p></section>
  <section class="f-card"><h3>Przebieg rekrutacji</h3><ol>${d.stages.map(s => `<li>${esc(s)}</li>`).join('')}</ol><p>Pierwsza reakcja: ${d.responseHours} godzin kalendarzowych. Decyzja: ${d.decisionHours} godzin kalendarzowych.</p><p>Rozmowy: ${d.interviewCount} · Assessment: ${d.assessmentMinutes} min</p><p>Zamknięcie: ${esc(date(d.closesAt))}</p></section>`;
}
export function processDetail(p: Process, skills: Skill[]) {
  const employer = p.viewer === 'EMPLOYER', terminal = ['HIRED','REJECTED','WITHDRAWN','CANCELLED'].includes(p.status);
  const commands = employer ? ['CLARIFY','ADVANCE','OFFER','REJECT','CANCEL'] : [...(p.stage === 'CLARIFICATION_REQUESTED' ? ['ANSWER'] : []), ...(p.status === 'OFFERED' ? ['ACCEPT_OFFER'] : []), 'WITHDRAW'];
  return `<h2>${esc(p.role)}</h2><p>${esc(p.company)}</p>${chip(label(p.status))}${chip(label(p.stage))}
    <section class="f-card"><h3>Dwa terminy, jasny proces</h3><dl class="f-facts"><dt>Pierwsza reakcja firmy</dt><dd>${p.firstResponseAt ? `Otrzymana ${esc(date(p.firstResponseAt))}` : esc(date(p.responseDueAt))}</dd><dt>Kolejny etap</dt><dd>${esc(date(p.stageDueAt))}</dd></dl><p>${esc(p.nextAction)}</p>${p.reason ? `<p>Powód zakończenia: ${esc(label(p.reason.code))} ${esc(skills.find(s => s.id === p.requirements.find(r => r.id === p.reason?.requirementId)?.skillId)?.label ?? '')}</p>` : ''}</section>
    <section class="f-card"><h3>${employer ? 'Profil w tym zgłoszeniu' : 'Dane udostępnione w zgłoszeniu'}</h3>${projection(p.projection)}</section>
    ${terminal ? '' : `<section class="f-card"><h3>Działania</h3>${form('process-command', select('command', 'Działanie', commands) + (employer ? area('nextAction', 'Treść pytania lub konkretne warunki następnego kroku', '', 'maxlength="1500"') + input('dueAt', 'Termin odpowiedzi / etapu', '', 'datetime-local', '') + select('reason', 'Powód odmowy', ['REQUIREMENT_NOT_DEMONSTRATED','REQUIREMENT_NOT_MET','OTHER_CANDIDATE_BETTER_MATCH','POSITION_FILLED','RECRUITMENT_CANCELLED']) + `<label>Wymaganie decydujące<select name="requirementId"><option value="">Wybierz wymaganie</option>${p.requirements.filter(r => r.kind !== 'WILL_TEACH').map(r => `<option value="${esc(r.id)}">${esc(skills.find(s => s.id === r.skillId)?.label ?? r.id)}</option>`).join('')}</select></label>` + area('explanation', 'Powód anulowania rekrutacji', '', 'maxlength="1000"') : area('answer', 'Odpowiedź na pytanie o kompetencje', '', 'maxlength="1500"')) + check('confirmed', 'Potwierdzam wybrane działanie.'), 'Zapisz działanie', p.id)}
    ${p.status === 'ACTIVE' || p.status === 'OFFERED' ? employer ? button('read-phone', 'Sprawdź dobrowolnie udostępniony telefon', p.id) : `<p>Telefon nie jest ujawniany automatycznie po przejściu etapu.</p>${button(p.contactGrant && !p.contactGrant.revoked_at ? 'revoke-phone' : 'grant-phone', p.contactGrant && !p.contactGrant.revoked_at ? 'Cofnij udostępnienie telefonu' : 'Udostępnij telefon tej rekrutacji', p.id)}` : ''}</section>`}
    <section class="f-card"><h3>Rozmowy</h3><div id="f-interview-list"></div>${employer && p.status === 'ACTIVE' && ['ACCEPTED_TO_NEXT_STAGE','ASSESSMENT_COMPLETED','INTERVIEW_COMPLETED'].includes(p.stage) ? `<details><summary>Zaproponuj termin rozmowy</summary><p>Godziny w strefie Twojego urządzenia; po zapisie pokazujemy je w Europe/Warsaw.</p>${form('interview-propose',input('startsAt','Początek rozmowy','','datetime-local')+input('endsAt','Koniec rozmowy','','datetime-local')+input('confirmBy','Potwierdzenie do','','datetime-local')+input('location','Miejsce lub sposób połączenia')+input('meetingUrl','Link spotkania (opcjonalnie)','','url','maxlength="2000"')+check('confirmed','Potwierdzam swoją dostępność w tym terminie.'),'Zaproponuj rozmowę',p.id)}</details>` : ''}</section>
    <section class="f-card"><h3>Assessmenty</h3><div id="f-attempt-list"></div>${employer && !terminal ? `<a class="f-button" href="#assessment-assign/${p.id}">Przypisz zatwierdzony assessment</a>` : ''}</section>
    <section class="f-card"><h3>Co zmieniło się od Twojego zgłoszenia?</h3>${p.changes.map(c => `<details class="f-row"><summary>${esc(label(c.field))}</summary><p>W chwili zgłoszenia: ${esc(JSON.stringify(c.before))}</p><p>Aktualnie: ${esc(JSON.stringify(c.after))}</p></details>`).join('') || '<p>Warunki pozostały bez zmian.</p>'}</section>
    <section class="f-card"><h3>Historia procesu</h3><ol class="f-timeline">${p.events.map(e => `<li><strong>${esc(label(e.kind))}</strong><br><small>${esc(date(e.occurred_at))}</small></li>`).join('')}</ol></section>
    <details class="f-card"><summary>Zgłoś problem z procesem</summary>${form('report', select('kind', 'Kategoria', ['CV_REQUEST','DISCRIMINATION','SCAM','PROCESS','ASSESSMENT_ABUSE','TECHNICAL_ISSUE']) + area('statement', 'Co się wydarzyło?', '', 'required minlength="10" maxlength="3000"'), 'Przekaż do przeglądu', p.id)}</details>`;
}
export function economicsView(o: Offer, e: Economics | null) {
  const s = e?.scenario;
  return `<h1>Twoja ekonomia tej pracy</h1><p>${esc(o.data.role)} · ${esc(o.company)}</p><p>Szacunki są prywatne. Netto podajesz ręcznie; nie uruchamiamy niezweryfikowanych reguł podatkowych. Koszt dojazdu podaj za ten sam okres co wynagrodzenie; czas dotyczy jednego dnia pracy.</p><section class="f-card">${form('economics', `<label>Wariant wynagrodzenia<select name="salaryOptionIndex">${o.data.salary.map((v, i) => `<option value="${i}" ${s?.salaryOptionIndex === i ? 'selected' : ''}>${esc(salary(v))}</option>`).join('')}</select></label>` + input('netMin', 'Szacowane netto od (PLN)', s?.netMin === null || s?.netMin === undefined ? '' : Number(s.netMin) / 100, 'number', 'min="0" step="0.01"') + input('netMax', 'Szacowane netto do (PLN)', s?.netMax === null || s?.netMax === undefined ? '' : Number(s.netMax) / 100, 'number', 'min="0" step="0.01"') + input('commuteCost', 'Dojazd za okres wynagrodzenia (PLN)', s?.commuteCost === null || s?.commuteCost === undefined ? '' : Number(s.commuteCost) / 100, 'number', 'min="0" step="0.01"') + input('commuteMinutes', 'Dojazd w obie strony na dzień (minuty)', s?.commuteMinutes, 'number', 'min="0"') + select('transport', 'Transport', ['CAR','TRANSIT','MIXED','NONE'], String(s?.transport ?? 'NONE')) + input('source', 'Źródło szacunku', s?.source ?? 'Własny szacunek') + input('observedAt', 'Data źródła', String(s?.observedAt ?? new Date().toISOString()).slice(0,10), 'date') + area('assumptions', 'Założenia szacunku', String(s?.assumptions ?? ''), 'required maxlength="1500"'), 'Zapisz prywatny szacunek', o.id)}</section>${e ? `<section class="f-card"><h2>Wynik scenariusza</h2><p>Netto: ${e.result.estimatedNetRange ? `${money(e.result.estimatedNetRange.min)} – ${money(e.result.estimatedNetRange.max)}` : 'Nie oszacowano'}</p><p>Po kosztach dojazdu: ${e.result.netAfterCommute ? `${money(e.result.netAfterCommute.min)} – ${money(e.result.netAfterCommute.max)}` : 'Nie oszacowano'}</p><p>Wersja oferty: ${e.offerVersion}${e.offerVersion !== o.version ? ' — warunki zmieniły się; przelicz scenariusz.' : ''}</p><p>${esc(e.result.source)} · ${esc(date(e.result.sourceDate))} · ${esc(e.result.calculationVersion)}</p><p>${esc(e.result.assumptions)}</p></section>` : ''}`;
}
export function attemptView(a: Attempt) {
  return `<h1>${esc(a.title)}</h1>${chip(label(a.state))}<section class="f-card"><dl class="f-facts"><dt>Typ</dt><dd>Quiz</dd><dt>Liczba zadań</dt><dd>${a.taskCount}</dd><dt>Limit od rozpoczęcia</dt><dd>${a.timeLimitMinutes} min</dd><dt>Przewidywany czas</dt><dd>${a.expectedMinutes} min</dd><dt>Ostateczny termin</dt><dd>${esc(date(a.deadline))}</dd></dl><p>Ocena odpowiedzi jest deterministyczna. Wynik otrzymasz po przeglądzie przez człowieka.</p>${a.state === 'INVITED' ? button('attempt-start', 'Rozpocznij assessment', a.id, true) : ''}${a.state === 'STARTED' ? `<p id="f-timer" role="timer">Koniec: ${esc(date(a.expiresAt))}</p><p class="f-muted">Termin jest ustalany na serwerze. Powrót do strony nie uruchamia czasu od nowa.</p>${form('attempt-answers', a.tasks.map(t => `<fieldset class="f-question"><legend>${esc(t.prompt)}</legend>${t.options.map((o, i) => `<label class="f-check"><input type="radio" name="${esc(t.id)}" value="${i}" ${a.answers[t.id] === i ? 'checked' : ''}>${esc(o)}</label>`).join('')}</fieldset>`).join('') + select('operation', 'Zapis lub zakończenie', ['Zapisz odpowiedzi','Prześlij do oceny']), 'Zapisz', a.id)}` : ''}${a.result ? `<h2>Wynik w tej rekrutacji</h2><p>${a.result.earned} / ${a.result.possible} punktów. Bez odpowiedzi: ${a.result.unanswered}.</p><p>${esc(a.result.reviewNote)}</p>` : ''}${a.state === 'SCORED_PENDING_REVIEW' && a.result ? form('attempt-review', area('note', 'Uzasadnienie przeglądu', '', 'required minlength="10" maxlength="1000"') + check('confirmed', 'Potwierdzam przegląd wyniku.'), 'Udostępnij wynik kandydatowi', a.id) : ''}</section><a href="#processes/${esc(a.processId)}">Wróć do procesu</a>`;
}
