export {};
type App={id:string;title:string|null;company:string|null;status:string};type Item={id:string;applicationId:string;company:string|null;title:string|null;messageExcerpt:string;suggestedOutcome:string;confidence:number;status:string;confirmedOutcome:string|null};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));async function api<T>(p:string,i:RequestInit={}):Promise<T>{const r=await fetch(p,{...i,headers:{...(i.body?{'content-type':'application/json'}:{}),...(i.headers??{})}});const d=await r.json().catch(()=>({})) as T&{error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??`HTTP ${r.status}`);return d;}
function ensure(){let s=document.querySelector<HTMLElement>('[data-screen="outcome-inbox"]');if(s)return s;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='outcome-inbox';m.textContent='Wyniki';mobile.append(m);const b=document.createElement('button');b.type='button';b.className='side-link';b.dataset.view='outcome-inbox';b.textContent='Skrzynka wyników';side.append(b);s=document.createElement('section');s.className='screen hidden';s.dataset.screen='outcome-inbox';s.innerHTML=`<div class="screen-heading"><p class="eyebrow">Outcome Inbox V2</p><h2>Co wydarzyło się z aplikacją?</h2><p>Wklej wiadomość od firmy. System tylko zasugeruje wynik — niczego nie zmieni bez Twojego potwierdzenia.</p></div><form id="outcomeInboxForm" class="card stack"><label>Aplikacja<select id="outcomeApplication" required></select></label><label>Treść wiadomości<textarea id="outcomeMessageText" rows="6" maxlength="5000" required></textarea></label><button class="button" type="submit">Sprawdź wiadomość</button></form><div id="outcomeInboxMessage" class="message" aria-live="polite"></div><div id="outcomeInboxList" class="stack"></div>`;content.append(s);for(const x of[m,b])x.addEventListener('click',()=>{location.hash='outcome-inbox';show();void load();});s.querySelector<HTMLFormElement>('#outcomeInboxForm')?.addEventListener('submit',e=>{e.preventDefault();void createSuggestion();});return s;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='outcome-inbox'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='outcome-inbox'));}
function message(t:string,error=false){const e=document.querySelector<HTMLElement>('#outcomeInboxMessage');if(e){e.textContent=t;e.className=`message ${error?'error':'success'}`;}}
function render(items:Item[]){const root=document.querySelector<HTMLElement>('#outcomeInboxList');if(!root)return;root.innerHTML=items.length?items.map(x=>`<article class="card"><div class="row-between"><h3>${esc(x.company??x.title??'Aplikacja')}</h3><span class="badge">${esc(x.status)}</span></div><p>${esc(x.messageExcerpt)}</p><p>Sugestia: <strong>${esc(x.suggestedOutcome)}</strong> · pewność ${Math.round(x.confidence*100)}%</p>${x.status==='PENDING'?`<div class="row"><button class="button" data-confirm="${esc(x.id)}">Potwierdź</button><button class="button button-secondary" data-dismiss="${esc(x.id)}">Odrzuć sugestię</button></div>`:`<p class="hint">Rozstrzygnięcie: ${esc(x.confirmedOutcome??x.status)}</p>`}</article>`).join(''):'<div class="card"><p>Brak wiadomości do sprawdzenia.</p></div>';root.querySelectorAll<HTMLButtonElement>('[data-confirm]').forEach(b=>b.addEventListener('click',()=>void resolve(b.dataset.confirm??'','confirm')));root.querySelectorAll<HTMLButtonElement>('[data-dismiss]').forEach(b=>b.addEventListener('click',()=>void resolve(b.dataset.dismiss??'','dismiss')));}
async function load(){try{const [apps,items]=await Promise.all([api<{applications:App[]}>('/api/applications'),api<{items:Item[]}>('/api/outcome-inbox')]);const select=document.querySelector<HTMLSelectElement>('#outcomeApplication');if(select)select.innerHTML=apps.applications.map(a=>`<option value="${esc(a.id)}">${esc(a.company??'Firma')} — ${esc(a.title??'oferta')} (${esc(a.status)})</option>`).join('');render(items.items);}catch(e){message((e as Error).message,true);}}
async function createSuggestion(){const applicationId=document.querySelector<HTMLSelectElement>('#outcomeApplication')?.value??'',text=document.querySelector<HTMLTextAreaElement>('#outcomeMessageText')?.value??'';try{await api('/api/outcome-inbox/suggestions',{method:'POST',body:JSON.stringify({applicationId,text})});message('Sugestia gotowa. Potwierdź ją dopiero po sprawdzeniu.');await load();}catch(e){message((e as Error).message,true);}}
async function resolve(id:string,action:'confirm'|'dismiss'){try{await api(`/api/outcome-inbox/${id}/${action}`,{method:'POST'});message(action==='confirm'?'Wynik potwierdzony i zapisany.':'Sugestia odrzucona.');await load();}catch(e){message((e as Error).message,true);}}
let enabled=false;async function refresh(){try{const d=await api<{features:{outcome_inbox?:boolean}}>('/api/features');enabled=d.features.outcome_inbox===true;if(enabled){ensure();if(location.hash==='#outcome-inbox'){show();await load();}}}catch{enabled=false;}}window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#outcome-inbox'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
