export {};
type Rec={key:string;headline:string;reason:string;action:string;confidence:string;sampleSize:number;scope:string};type Report={recommendations:Rec[];confidence:string;message:string;minimumApplications:number};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));async function api<T>(p:string):Promise<T>{const r=await fetch(p);const d=await r.json().catch(()=>({})) as T&{error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??`HTTP ${r.status}`);return d;}
function ensure(){let s=document.querySelector<HTMLElement>('[data-screen="strategy"]');if(s)return s;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='strategy';m.textContent='Strategia';mobile.append(m);const b=document.createElement('button');b.type='button';b.className='side-link';b.dataset.view='strategy';b.textContent='Strategia';side.append(b);s=document.createElement('section');s.className='screen hidden';s.dataset.screen='strategy';s.innerHTML=`<div class="screen-heading"><p class="eyebrow">Strategy Engine V2</p><h2>Co warto zmienić w strategii?</h2><p>Rekomendacje pojawiają się dopiero przy wystarczającej próbce. Są hipotezami do małych eksperymentów, nie wyrokami o karierze.</p></div><div id="strategyMessage" class="message" aria-live="polite"></div><div id="strategyResult" class="stack"></div>`;content.append(s);for(const x of[m,b])x.addEventListener('click',()=>{location.hash='strategy';show();void load();});return s;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='strategy'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='strategy'));}
function render(r:Report){const root=document.querySelector<HTMLElement>('#strategyResult');if(!root)return;root.innerHTML=`<div class="card"><div class="row-between"><h3>Poziom pewności</h3><span class="badge">${esc(r.confidence.replaceAll('_',' '))}</span></div><p>${esc(r.message)}</p></div>${r.recommendations.map(x=>`<article class="card"><div class="row-between"><h3>${esc(x.headline)}</h3><span class="badge">${esc(x.confidence.replaceAll('_',' '))}</span></div><p>${esc(x.reason)}</p><p><strong>Mały eksperyment:</strong> ${esc(x.action)}</p><p class="hint">Próbka: ${x.sampleSize} · ${esc(x.scope)}</p></article>`).join('')}`;}
function msg(t:string,e=false){const x=document.querySelector<HTMLElement>('#strategyMessage');if(x){x.textContent=t;x.className=`message ${e?'error':'success'}`;}}
async function load(){try{const d=await api<{report:Report}>('/api/strategy');render(d.report);msg('Strategia przeliczona na aktualnych danych.');}catch(e){msg((e as Error).message,true);}}
let enabled=false;async function refresh(){try{const d=await api<{features:{strategy_engine?:boolean}}>('/api/features');enabled=d.features.strategy_engine===true;if(enabled){ensure();if(location.hash==='#strategy'){show();await load();}}}catch{enabled=false;}}window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#strategy'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
